import {
  QUERY_FIELD_SOURCE,
  ENDATO_PS_PERSON_ENTITY_TYPE,
  ENDATO_CE_PERSON_ENTITY_TYPE,
  PERSON_SOURCE_ENTITY_TYPES as PERSON_SOURCE_TYPES,
  DEFAULT_SOURCE_FILTER_VALUES,
  DEFAULT_PERSON_INCLUDES as CORE_DEFAULT_PERSON_INCLUDES,
  DEFAULT_PERSON_SELECT_FIELDS as CORE_DEFAULT_PERSON_SELECT_FIELDS,
} from "../../../packages/lyo-person-api-client/dist/index.js";

export {
  QUERY_FIELD_SOURCE,
  ENDATO_PS_PERSON_ENTITY_TYPE,
  ENDATO_CE_PERSON_ENTITY_TYPE,
  PERSON_SOURCE_TYPES,
  DEFAULT_SOURCE_FILTER_VALUES,
};

export const DEFAULT_PERSON_INCLUDES = Array.isArray(CORE_DEFAULT_PERSON_INCLUDES)
  ? CORE_DEFAULT_PERSON_INCLUDES.join(",")
  : CORE_DEFAULT_PERSON_INCLUDES;

export const DEFAULT_PERSON_SELECT_FIELDS = Array.isArray(CORE_DEFAULT_PERSON_SELECT_FIELDS)
  ? CORE_DEFAULT_PERSON_SELECT_FIELDS.join(",")
  : CORE_DEFAULT_PERSON_SELECT_FIELDS;
