// <auto-generated />
using System;
using Lyo.Favorite.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Favorite.Postgres.Migrations
{
    [DbContext(typeof(FavoriteDbContext))]
    partial class FavoriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("favorite")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Favorite.Postgres.Database.FavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("ForEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_type");

                    b.Property<string>("FromEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_type");

                    b.HasKey("Id");

                    b.HasIndex("ForEntityType", "ForEntityId")
                        .HasDatabaseName("ix_favorite_for_entity");

                    b.HasIndex("FromEntityType", "FromEntityId")
                        .HasDatabaseName("ix_favorite_from_entity");

                    b.HasIndex("ForEntityType", "ForEntityId", "FromEntityType", "FromEntityId")
                        .IsUnique()
                        .HasDatabaseName("uq_favorite_for_from_entity");

                    b.ToTable("favorite", "favorite");
                });
#pragma warning restore 612, 618
        }
    }
}
