// <auto-generated />
using System;
using Lyo.Audit.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lyo.Audit.Postgres.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260220200959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Lyo.Audit.Postgres.Database.AuditChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangedPropertiesJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_properties_json");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("ForEntityId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_entity_type");

                    b.Property<string>("FromEntityId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from_entity_type");

                    b.Property<string>("OldValuesJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values_json");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ForEntityType")
                        .HasDatabaseName("ix_audit_changes_for_entity_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_changes_timestamp");

                    b.HasIndex("ForEntityType", "ForEntityId", "Timestamp")
                        .HasDatabaseName("ix_audit_changes_for_entity_timestamp");

                    b.HasIndex("FromEntityType", "FromEntityId")
                        .HasDatabaseName("ix_audit_changes_from_entity");

                    b.ToTable("audit_changes", "audit");
                });

            modelBuilder.Entity("Lyo.Audit.Postgres.Database.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("ForEntityId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_entity_type");

                    b.Property<string>("FromEntityId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from_entity_type");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_audit_events_event_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_events_timestamp");

                    b.HasIndex("EventType", "Timestamp")
                        .HasDatabaseName("ix_audit_events_event_type_timestamp");

                    b.HasIndex("ForEntityType", "ForEntityId", "Timestamp")
                        .HasDatabaseName("ix_audit_events_for_entity_timestamp");

                    b.HasIndex("FromEntityType", "FromEntityId")
                        .HasDatabaseName("ix_audit_events_from_entity");

                    b.ToTable("audit_events", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
