<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <Description>Date and time utilities and services for the Lyo library suite.</Description>
        <PackageTags>date time datetime utilities</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Common\Lyo.Common.Metadata\Lyo.Common.Metadata.csproj"/>
        <ProjectReference Include="..\..\Exceptions\Lyo.Exceptions\Lyo.Exceptions.csproj"/>
    </ItemGroup>

</Project>