// <auto-generated />
using System;
using Lyo.Drift.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Drift.Postgres.Migrations
{
    [DbContext(typeof(DriftDbContext))]
    [Migration("20260903223114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("drift")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftChangeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("change_json");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("WatchRoot")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("watch_root");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "WatchRoot", "OccurredAtUtc")
                        .HasDatabaseName("ix_drift_change_instance_root_occurred");

                    b.ToTable("change_event", "drift");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftDiffSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at_utc");

                    b.Property<string>("FileChangesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("file_changes_json");

                    b.Property<Guid?>("FromSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_snapshot_id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SystemDifferencesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("system_differences_json");

                    b.Property<Guid>("ToSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("ToSnapshotId")
                        .HasDatabaseName("ix_drift_diff_to_snapshot");

                    b.HasIndex("InstanceId", "ComputedAtUtc")
                        .HasDatabaseName("ix_drift_diff_instance_computed");

                    b.ToTable("diff_snapshot", "drift");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("instance_key");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_name");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("process_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("WatchesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("watches_json");

                    b.HasKey("Id");

                    b.HasIndex("InstanceKey")
                        .IsUnique()
                        .HasDatabaseName("ux_drift_instance_key");

                    b.ToTable("instance", "drift");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftStructureSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentHashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_hash_algorithm");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SystemInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("system_info_json");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at_utc");

                    b.Property<string>("TreeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("tree_json");

                    b.Property<string>("WatchRoot")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("watch_root");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Kind", "WatchRoot", "ContentHashAlgorithm", "ContentHash")
                        .HasDatabaseName("ix_drift_snapshot_lineage_hash");

                    b.HasIndex("InstanceId", "Kind", "WatchRoot", "TakenAtUtc")
                        .HasDatabaseName("ix_drift_snapshot_lineage_taken");

                    b.ToTable("structure_snapshot", "drift");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftChangeEvent", b =>
                {
                    b.HasOne("Lyo.Drift.Postgres.Database.DriftInstance", "Instance")
                        .WithMany("Changes")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftDiffSnapshot", b =>
                {
                    b.HasOne("Lyo.Drift.Postgres.Database.DriftInstance", "Instance")
                        .WithMany("Diffs")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftStructureSnapshot", b =>
                {
                    b.HasOne("Lyo.Drift.Postgres.Database.DriftInstance", "Instance")
                        .WithMany("Snapshots")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Lyo.Drift.Postgres.Database.DriftInstance", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Diffs");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
