// <auto-generated />
using System;
using Lyo.Rating.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Rating.Postgres.Migrations
{
    [DbContext(typeof(RatingDbContext))]
    [Migration("20260510032205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rating")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Rating.Postgres.Database.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("DeletedByType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deleted_by_type");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("dislike_count");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ForEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_type");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_type");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("private")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_rating_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_rating_expires_at")
                        .HasFilter("\"expires_at\" IS NOT NULL");

                    b.HasIndex("TenantId", "Context")
                        .HasDatabaseName("ix_rating_tenant_context");

                    b.HasIndex("TenantId", "ForEntityType", "ForEntityId")
                        .HasDatabaseName("ix_rating_tenant_for_entity");

                    b.HasIndex("TenantId", "FromEntityType", "FromEntityId")
                        .HasDatabaseName("ix_rating_tenant_from_entity");

                    b.HasIndex("TenantId", "ForEntityType", "ForEntityId", "FromEntityType", "FromEntityId", "Subject")
                        .HasDatabaseName("ix_rating_tenant_for_from_subject");

                    b.ToTable("rating", "rating");
                });

            modelBuilder.Entity("Lyo.Rating.Postgres.Database.RatingReactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<Guid>("ForEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_type");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_type");

                    b.Property<int>("ReactionType")
                        .HasColumnType("integer")
                        .HasColumnName("reaction_type");

                    b.HasKey("Id");

                    b.HasIndex("ForEntityType", "ForEntityId")
                        .HasDatabaseName("ix_rating_reaction_for_entity");

                    b.HasIndex("ForEntityType", "ForEntityId", "FromEntityType", "FromEntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_rating_reaction_for_from");

                    b.ToTable("rating_reaction", "rating");
                });
#pragma warning restore 612, 618
        }
    }
}
