#!/usr/bin/env python3
"""Render adhoc tooling READMEs from docs.json (source of truth).

Lightweight schema (not package.schema.json):
  id, name, tagline, description, commands[{cmd, blurb}], notes[], readmePath

Usage:
  python3 scripts/docs/tooling-docs.py render
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

TOOLING_DOCS: list[Path] = [
    ROOT / "scripts" / "benchmarks" / "docs.json",
    ROOT / "scripts" / "docker" / "docs.json",
    ROOT / "scripts" / "nuget" / "docs.json",
    ROOT / "k6" / "framework-person" / "docs.json",
    ROOT
    / "Lyo.Net"
    / "Data"
    / "Images"
    / "Lyo.Images.Ocr.Tesseract"
    / "scripts"
    / "docs.json",
]


def _load(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"{path}: expected object")
    for key in ("id", "name", "readmePath"):
        if not data.get(key):
            raise SystemExit(f"{path}: missing required field {key!r}")
    return data


def docs_to_readme(doc: dict) -> str:
    lines: list[str] = [
        f"# {doc['name']}",
        "",
    ]
    if doc.get("tagline"):
        lines += [doc["tagline"], ""]
    if doc.get("description"):
        lines += [doc["description"].rstrip(), ""]

    commands = doc.get("commands") or []
    if commands:
        lines += ["## Commands", ""]
        for item in commands:
            cmd = (item.get("cmd") or "").strip()
            blurb = (item.get("blurb") or "").strip()
            if not cmd:
                continue
            if blurb:
                lines.append(f"- `{cmd}` — {blurb}")
            else:
                lines.append(f"- `{cmd}`")
        lines.append("")

    notes = doc.get("notes") or []
    if notes:
        lines += ["## Notes", ""]
        for note in notes:
            lines.append(f"- {note}")
        lines.append("")

    lines.append("<!-- Generated by scripts/docs/tooling-docs.py — edit docs.json, not this file. -->")
    lines.append("")
    return "\n".join(lines)


def render() -> int:
    written = 0
    for path in TOOLING_DOCS:
        if not path.is_file():
            print(f"warn: missing {path.relative_to(ROOT)}", file=sys.stderr)
            continue
        doc = _load(path)
        readme = ROOT / doc["readmePath"]
        readme.parent.mkdir(parents=True, exist_ok=True)
        readme.write_text(docs_to_readme(doc), encoding="utf-8")
        print(f"tooling-docs: wrote {doc['readmePath']}")
        written += 1
    print(f"tooling-docs: {written} README(s)")
    return 0 if written else 1


def main(argv: list[str] | None = None) -> int:
    args = list(argv if argv is not None else sys.argv[1:])
    cmd = (args[0] if args else "render").lower()
    if cmd == "render":
        return render()
    print("Usage: tooling-docs.py render", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
