// <auto-generated />
using System;
using System.Collections.Generic;
using Lyo.Job.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Job.Postgres.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("job")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobBlackoutCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_blackout_calendar");

                    b.HasIndex(new[] { "Name" }, "ix_job_blackout_calendar_name");

                    b.ToTable("job_blackout_calendar", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobBlackoutWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DayFlags")
                        .IsRequired()
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("day_flags");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_utc");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("end_time");

                    b.Property<Guid>("JobBlackoutCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_blackout_calendar_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Skip")
                        .HasColumnName("policy");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_blackout_window");

                    b.HasIndex(new[] { "JobBlackoutCalendarId" }, "ix_job_blackout_window_job_blackout_calendar_id");

                    b.ToTable("job_blackout_window", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlertAfterConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alert_after_consecutive_failures");

                    b.Property<bool>("AlertOnFailure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alert_on_failure");

                    b.Property<string>("AlertWebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alert_webhook_url");

                    b.Property<int>("CircuitBreakerResetMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("circuit_breaker_reset_minutes");

                    b.Property<int>("CircuitBreakerThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("circuit_breaker_threshold");

                    b.Property<DateTime?>("CircuitBreakerTrippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("circuit_breaker_tripped_at");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<int>("DefinitionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("definition_version");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("ExpectedDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("expected_duration_minutes");

                    b.Property<int>("MaxConcurrentRuns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_concurrent_runs");

                    b.Property<int>("MaxRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_retry_count");

                    b.Property<int>("MaxRunsPerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_runs_per_hour");

                    b.Property<int>("MustStartByMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("must_start_by_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<int>("RetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retention_days");

                    b.Property<int>("RetryBackoffSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_backoff_seconds");

                    b.Property<string>("RetryBackoffType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("Linear")
                        .HasColumnName("retry_backoff_type");

                    b.Property<int>("TimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("timeout_minutes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("worker_type");

                    b.HasKey("Id")
                        .HasName("pk_job_definition");

                    b.HasIndex(new[] { "Name" }, "ix_job_definition_name");

                    b.ToTable("job_definition", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobFileUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<int>("DataEncryptionKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("data_encryption_key_version");

                    b.Property<byte[]>("EncryptedDataEncryptionKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_data_encryption_key");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_filename");

                    b.Property<byte[]>("OriginalHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("original_hash");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("original_size");

                    b.Property<string>("SourceDirectory")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("source_directory");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_filename");

                    b.Property<byte[]>("SourceHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("source_hash");

                    b.Property<long>("SourceSize")
                        .HasColumnType("bigint")
                        .HasColumnName("source_size");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<DateTime>("UploadTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_file_upload");

                    b.HasIndex(new[] { "OriginalHash" }, "ix_job_file_upload_original_hash");

                    b.HasIndex(new[] { "SourceHash" }, "ix_job_file_upload_source_hash");

                    b.ToTable("job_file_upload", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobParallelRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BaseJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_job_definition_id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("OtherJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("other_job_definition_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_parallel_restriction");

                    b.HasIndex(new[] { "BaseJobDefinitionId" }, "ix_job_parallel_restriction_base_job_definition_id");

                    b.HasIndex(new[] { "OtherJobDefinitionId" }, "ix_job_parallel_restriction_other_job_definition_id");

                    b.ToTable("job_parallel_restriction", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AllowMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_multiple");

                    b.Property<string>("AllowedValues")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allowed_values");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<byte[]>("EncryptedValue")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_value");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("ValidationRegex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("validation_regex");

                    b.Property<string>("Value")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_job_parameter");

                    b.HasIndex(new[] { "JobDefinitionId" }, "ix_job_parameter_job_definition_id");

                    b.HasIndex(new[] { "Key" }, "ix_job_parameter_key");

                    b.ToTable("job_parameter", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AllowTriggers")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_triggers");

                    b.Property<int?>("BatchIndex")
                        .HasColumnType("integer")
                        .HasColumnName("batch_index");

                    b.Property<int?>("BatchTotal")
                        .HasColumnType("integer")
                        .HasColumnName("batch_total");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<int?>("DefinitionAuditVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_audit_version");

                    b.Property<bool>("DryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("dry_run");

                    b.Property<DateTime?>("FinishedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_timestamp");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<Guid?>("JobScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_schedule_id");

                    b.Property<Guid?>("JobTriggerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_trigger_id");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<Guid?>("ParentJobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_job_run_id");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("progress_message");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid?>("ReRanFromJobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("re_ran_from_job_run_id");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<int>("RetryAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_attempt");

                    b.Property<DateTime?>("ScheduledSlotUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_slot_utc");

                    b.Property<bool>("SlaBreached")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sla_breached");

                    b.Property<DateTime?>("StartedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_timestamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("TriggeredByJobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_job_run_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_run");

                    b.HasIndex("ReRanFromJobRunId");

                    b.HasIndex("JobDefinitionId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_job_run_idempotency_key_unique")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("JobScheduleId", "ScheduledSlotUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_job_run_schedule_slot_unique")
                        .HasFilter("job_schedule_id IS NOT NULL AND scheduled_slot_utc IS NOT NULL");

                    b.HasIndex(new[] { "JobDefinitionId" }, "ix_job_run_job_definition_id");

                    b.HasIndex(new[] { "JobScheduleId" }, "ix_job_run_job_schedule_id");

                    b.HasIndex(new[] { "JobTriggerId" }, "ix_job_run_job_trigger_id");

                    b.HasIndex(new[] { "ParentJobRunId" }, "ix_job_run_parent_job_run_id");

                    b.HasIndex(new[] { "State" }, "ix_job_run_state");

                    b.HasIndex(new[] { "TriggeredByJobRunId" }, "ix_job_run_triggered_by_job_run_id");

                    b.ToTable("job_run", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRunLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Context")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("context");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("stack_trace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_run_log");

                    b.HasIndex(new[] { "JobRunId" }, "ix_job_run_log_job_run_id");

                    b.HasIndex(new[] { "Level" }, "ix_job_run_log_level");

                    b.ToTable("job_run_log", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRunParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<byte[]>("EncryptedValue")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_value");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_job_run_parameter");

                    b.HasIndex(new[] { "JobRunId" }, "ix_job_run_parameter_job_run_id");

                    b.HasIndex(new[] { "Key" }, "ix_job_run_parameter_key");

                    b.ToTable("job_run_parameter", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRunResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_job_run_result");

                    b.HasIndex(new[] { "JobRunId" }, "ix_job_run_result_job_run_id");

                    b.HasIndex(new[] { "Key" }, "ix_job_run_result_key");

                    b.ToTable("job_run_result", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cron_expression");

                    b.Property<string>("DayFlags")
                        .IsRequired()
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("day_flags");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_utc");

                    b.Property<string>("EndTime")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("end_time");

                    b.Property<int?>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<Guid?>("JobBlackoutCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_blackout_calendar_id");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<string>("MisfirePolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("Skip")
                        .HasColumnName("misfire_policy");

                    b.Property<string>("MonthFlags")
                        .IsRequired()
                        .HasMaxLength(108)
                        .HasColumnType("character varying(108)")
                        .HasColumnName("month_flags");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<string>("StartTime")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("start_time");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.PrimitiveCollection<List<string>>("Times")
                        .HasColumnType("character varying(8)[]")
                        .HasColumnName("times");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_schedule");

                    b.HasIndex(new[] { "JobBlackoutCalendarId" }, "ix_job_schedule_job_blackout_calendar_id");

                    b.HasIndex(new[] { "JobDefinitionId" }, "ix_job_schedule_job_definition_id");

                    b.ToTable("job_schedule", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobScheduleParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("JobScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_schedule_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("Value")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_job_schedule_parameter");

                    b.HasIndex(new[] { "JobScheduleId" }, "ix_job_schedule_parameter_job_schedule_id");

                    b.HasIndex(new[] { "Key" }, "ix_job_schedule_parameter_key");

                    b.ToTable("job_schedule_parameter", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<string>("TriggerComparator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_comparator");

                    b.Property<string>("TriggerJobResultKey")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("trigger_job_result_key");

                    b.Property<string>("TriggerJobResultValue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_job_result_value");

                    b.Property<Guid>("TriggersJobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggers_job_definition_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_trigger");

                    b.HasIndex(new[] { "JobDefinitionId" }, "ix_job_trigger_job_definition_id");

                    b.HasIndex(new[] { "TriggerJobResultKey" }, "ix_job_trigger_trigger_job_result_key");

                    b.HasIndex(new[] { "TriggersJobDefinitionId" }, "ix_job_trigger_triggers_job_definition_id");

                    b.ToTable("job_trigger", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobTriggerParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid>("JobTriggerId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_trigger_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("Value")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_job_trigger_parameter");

                    b.HasIndex(new[] { "JobTriggerId" }, "ix_job_trigger_parameter_job_trigger_id");

                    b.HasIndex(new[] { "Key" }, "ix_job_trigger_parameter_key");

                    b.ToTable("job_trigger_parameter", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<int>("InFlightCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("in_flight_count");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("machine_name");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("process_id");

                    b.Property<DateTime>("StartedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_timestamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("worker_type");

                    b.HasKey("Id")
                        .HasName("pk_job_worker_instance");

                    b.HasIndex(new[] { "LastHeartbeatUtc" }, "ix_job_worker_instance_last_heartbeat_utc");

                    b.HasIndex(new[] { "WorkerType" }, "ix_job_worker_instance_worker_type");

                    b.ToTable("job_worker_instance", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_workflow");

                    b.HasIndex(new[] { "Name" }, "ix_job_workflow_name");

                    b.ToTable("job_workflow", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime?>("FinishedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_timestamp");

                    b.Property<Guid>("JobWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_workflow_id");

                    b.Property<DateTime?>("StartedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_timestamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_workflow_run");

                    b.HasIndex(new[] { "JobWorkflowId" }, "ix_job_workflow_run_job_workflow_id");

                    b.HasIndex(new[] { "State" }, "ix_job_workflow_run_state");

                    b.ToTable("job_workflow_run", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowRunStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<Guid?>("JobRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_run_id");

                    b.Property<Guid>("JobWorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_workflow_run_id");

                    b.Property<Guid>("JobWorkflowStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_workflow_step_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_workflow_run_step");

                    b.HasIndex(new[] { "JobRunId" }, "ix_job_workflow_run_step_job_run_id");

                    b.HasIndex(new[] { "JobWorkflowRunId" }, "ix_job_workflow_run_step_job_workflow_run_id");

                    b.HasIndex(new[] { "JobWorkflowStepId" }, "ix_job_workflow_run_step_job_workflow_step_id");

                    b.ToTable("job_workflow_run_step", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DependsOnStepIds")
                        .HasColumnType("text")
                        .HasColumnName("depends_on_step_ids");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FailurePolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Stop")
                        .HasColumnName("failure_policy");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<Guid>("JobWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_workflow_id");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("text")
                        .HasColumnName("parameters_json");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("step_name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id")
                        .HasName("pk_job_workflow_step");

                    b.HasIndex(new[] { "JobDefinitionId" }, "ix_job_workflow_step_job_definition_id");

                    b.HasIndex(new[] { "JobWorkflowId" }, "ix_job_workflow_step_job_workflow_id");

                    b.ToTable("job_workflow_step", "job");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobBlackoutWindow", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobBlackoutCalendar", "JobBlackoutCalendar")
                        .WithMany("JobBlackoutWindows")
                        .HasForeignKey("JobBlackoutCalendarId")
                        .IsRequired()
                        .HasConstraintName("fk_job_blackout_window_job_blackout_calendar_job_blackout_calendar_id");

                    b.Navigation("JobBlackoutCalendar");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobParallelRestriction", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "BaseJobDefinition")
                        .WithMany("JobParallelRestrictionBaseJobDefinitions")
                        .HasForeignKey("BaseJobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_parallel_restriction_base");

                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "OtherJobDefinition")
                        .WithMany("JobParallelRestrictionOtherJobDefinitions")
                        .HasForeignKey("OtherJobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_parallel_restriction_other");

                    b.Navigation("BaseJobDefinition");

                    b.Navigation("OtherJobDefinition");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobParameter", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "JobDefinition")
                        .WithMany("JobParameters")
                        .HasForeignKey("JobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_parameter_job_definition_job_definition_id");

                    b.Navigation("JobDefinition");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRun", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "JobDefinition")
                        .WithMany("JobRuns")
                        .HasForeignKey("JobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_run_job_definition_job_definition_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobSchedule", "JobSchedule")
                        .WithMany("JobRuns")
                        .HasForeignKey("JobScheduleId")
                        .HasConstraintName("fk_job_run_job_schedule_job_schedule_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobTrigger", "JobTrigger")
                        .WithMany("JobRuns")
                        .HasForeignKey("JobTriggerId")
                        .HasConstraintName("fk_job_run_job_trigger_job_trigger_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "ParentJobRun")
                        .WithMany("InverseParentJobRun")
                        .HasForeignKey("ParentJobRunId")
                        .HasConstraintName("fk_job_run_parent");

                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "ReRanFromJobRun")
                        .WithMany("InverseReRanFromJobRun")
                        .HasForeignKey("ReRanFromJobRunId")
                        .HasConstraintName("fk_job_run_re_ran_from");

                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "TriggeredByJobRun")
                        .WithMany("InverseTriggeredByJobRun")
                        .HasForeignKey("TriggeredByJobRunId")
                        .HasConstraintName("fk_job_run_triggered_by");

                    b.Navigation("JobDefinition");

                    b.Navigation("JobSchedule");

                    b.Navigation("JobTrigger");

                    b.Navigation("ParentJobRun");

                    b.Navigation("ReRanFromJobRun");

                    b.Navigation("TriggeredByJobRun");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRunLog", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "JobRun")
                        .WithMany("JobRunLogs")
                        .HasForeignKey("JobRunId")
                        .IsRequired()
                        .HasConstraintName("fk_job_run_log_job_run_job_run_id");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRunParameter", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "JobRun")
                        .WithMany("JobRunParameters")
                        .HasForeignKey("JobRunId")
                        .IsRequired()
                        .HasConstraintName("fk_job_run_parameter_job_run_job_run_id");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRunResult", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "JobRun")
                        .WithMany("JobRunResults")
                        .HasForeignKey("JobRunId")
                        .IsRequired()
                        .HasConstraintName("fk_job_run_result_job_run_job_run_id");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobSchedule", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobBlackoutCalendar", "JobBlackoutCalendar")
                        .WithMany("JobSchedules")
                        .HasForeignKey("JobBlackoutCalendarId")
                        .HasConstraintName("fk_job_schedule_job_blackout_calendar_job_blackout_calendar_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "JobDefinition")
                        .WithMany("JobSchedules")
                        .HasForeignKey("JobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_schedule_job_definition_job_definition_id");

                    b.Navigation("JobBlackoutCalendar");

                    b.Navigation("JobDefinition");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobScheduleParameter", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobSchedule", "JobSchedule")
                        .WithMany("JobScheduleParameters")
                        .HasForeignKey("JobScheduleId")
                        .IsRequired()
                        .HasConstraintName("fk_job_schedule_parameter_job_schedule_job_schedule_id");

                    b.Navigation("JobSchedule");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobTrigger", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "JobDefinition")
                        .WithMany("JobTriggerJobDefinitions")
                        .HasForeignKey("JobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_trigger_job_definition_job_definition_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "TriggersJobDefinition")
                        .WithMany("JobTriggerTriggersJobDefinitions")
                        .HasForeignKey("TriggersJobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_trigger_triggers_job_definition");

                    b.Navigation("JobDefinition");

                    b.Navigation("TriggersJobDefinition");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobTriggerParameter", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobTrigger", "JobTrigger")
                        .WithMany("JobTriggerParameters")
                        .HasForeignKey("JobTriggerId")
                        .IsRequired()
                        .HasConstraintName("fk_job_trigger_parameter_job_trigger_job_trigger_id");

                    b.Navigation("JobTrigger");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowRun", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobWorkflow", "JobWorkflow")
                        .WithMany("JobWorkflowRuns")
                        .HasForeignKey("JobWorkflowId")
                        .IsRequired()
                        .HasConstraintName("fk_job_workflow_run_job_workflow_job_workflow_id");

                    b.Navigation("JobWorkflow");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowRunStep", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobRun", "JobRun")
                        .WithMany("JobWorkflowRunSteps")
                        .HasForeignKey("JobRunId")
                        .HasConstraintName("fk_job_workflow_run_step_job_run_job_run_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobWorkflowRun", "JobWorkflowRun")
                        .WithMany("JobWorkflowRunSteps")
                        .HasForeignKey("JobWorkflowRunId")
                        .IsRequired()
                        .HasConstraintName("fk_job_workflow_run_step_job_workflow_run_job_workflow_run_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobWorkflowStep", "JobWorkflowStep")
                        .WithMany("JobWorkflowRunSteps")
                        .HasForeignKey("JobWorkflowStepId")
                        .IsRequired()
                        .HasConstraintName("fk_job_workflow_run_step_job_workflow_step_job_workflow_step_id");

                    b.Navigation("JobRun");

                    b.Navigation("JobWorkflowRun");

                    b.Navigation("JobWorkflowStep");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowStep", b =>
                {
                    b.HasOne("Lyo.Job.Postgres.Database.JobDefinition", "JobDefinition")
                        .WithMany("JobWorkflowSteps")
                        .HasForeignKey("JobDefinitionId")
                        .IsRequired()
                        .HasConstraintName("fk_job_workflow_step_job_definition_job_definition_id");

                    b.HasOne("Lyo.Job.Postgres.Database.JobWorkflow", "JobWorkflow")
                        .WithMany("JobWorkflowSteps")
                        .HasForeignKey("JobWorkflowId")
                        .IsRequired()
                        .HasConstraintName("fk_job_workflow_step_job_workflow_job_workflow_id");

                    b.Navigation("JobDefinition");

                    b.Navigation("JobWorkflow");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobBlackoutCalendar", b =>
                {
                    b.Navigation("JobBlackoutWindows");

                    b.Navigation("JobSchedules");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobDefinition", b =>
                {
                    b.Navigation("JobParallelRestrictionBaseJobDefinitions");

                    b.Navigation("JobParallelRestrictionOtherJobDefinitions");

                    b.Navigation("JobParameters");

                    b.Navigation("JobRuns");

                    b.Navigation("JobSchedules");

                    b.Navigation("JobTriggerJobDefinitions");

                    b.Navigation("JobTriggerTriggersJobDefinitions");

                    b.Navigation("JobWorkflowSteps");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobRun", b =>
                {
                    b.Navigation("InverseParentJobRun");

                    b.Navigation("InverseReRanFromJobRun");

                    b.Navigation("InverseTriggeredByJobRun");

                    b.Navigation("JobRunLogs");

                    b.Navigation("JobRunParameters");

                    b.Navigation("JobRunResults");

                    b.Navigation("JobWorkflowRunSteps");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobSchedule", b =>
                {
                    b.Navigation("JobRuns");

                    b.Navigation("JobScheduleParameters");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobTrigger", b =>
                {
                    b.Navigation("JobRuns");

                    b.Navigation("JobTriggerParameters");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflow", b =>
                {
                    b.Navigation("JobWorkflowRuns");

                    b.Navigation("JobWorkflowSteps");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowRun", b =>
                {
                    b.Navigation("JobWorkflowRunSteps");
                });

            modelBuilder.Entity("Lyo.Job.Postgres.Database.JobWorkflowStep", b =>
                {
                    b.Navigation("JobWorkflowRunSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
