// <auto-generated />
using System;
using Lyo.Comic.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Comic.Postgres.Migrations
{
    [DbContext(typeof(ComicDbContext))]
    [Migration("20260421000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("comic")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.AlternateTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_alternate_title_series");

                    b.HasIndex("SeriesId", "Title", "Language")
                        .HasDatabaseName("ix_comic_alternate_title_series_title_lang");

                    b.ToTable("alternate_title", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.ChapterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ChapterNumber")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("chapter_number");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<Guid?>("VolumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("volume_id");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_chapter_series");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_comic_chapter_volume");

                    b.HasIndex("SeriesId", "ChapterNumber", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_comic_chapter_series_num_lang");

                    b.ToTable("chapter", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.SeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ComicType")
                        .HasColumnType("integer")
                        .HasColumnName("comic_type");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("original_language");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("integer")
                        .HasColumnName("published_year");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_comic_series_slug");

                    b.HasIndex("ComicType")
                        .HasDatabaseName("ix_comic_series_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_comic_series_status");

                    b.ToTable("series", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.VolumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverImageRef")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_ref");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<decimal?>("VolumeNumber")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("volume_number");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_volume_series");

                    b.HasIndex("SeriesId", "VolumeNumber")
                        .HasDatabaseName("ix_comic_volume_series_number");

                    b.ToTable("volume", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.AlternateTitleEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("AlternateTitles")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.ChapterEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyo.Comic.Postgres.Database.VolumeEntity", "Volume")
                        .WithMany("Chapters")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.VolumeEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("Volumes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.SeriesEntity", b =>
                {
                    b.Navigation("AlternateTitles");

                    b.Navigation("Chapters");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.VolumeEntity", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
