// <auto-generated />
using System;
using Lyo.Comic.Enums;
using Lyo.Comic.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Comic.Postgres.Migrations
{
    [DbContext(typeof(ComicDbContext))]
    [Migration("20260421000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("comic")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterEntityVolumeEntity", b =>
                {
                    b.Property<Guid>("CharactersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VolumesId")
                        .HasColumnType("uuid");

                    b.HasKey("CharactersId", "VolumesId");

                    b.HasIndex("VolumesId");

                    b.ToTable("character_volume", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.AlternateTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_alternate_title_series");

                    b.HasIndex("SeriesId", "Title", "Language")
                        .HasDatabaseName("ix_comic_alternate_title_series_title_lang");

                    b.ToTable("alternate_title", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.ChapterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ChapterNumber")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("chapter_number");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<Guid?>("VolumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("volume_id");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_chapter_series");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_comic_chapter_volume");

                    b.HasIndex("SeriesId", "ChapterNumber", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_comic_chapter_series_num_lang");

                    b.ToTable("chapter", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("description");

                    b.Property<string>("ImageRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_ref");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_comic_character_name");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_character_series");

                    b.ToTable("character", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.PageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImageRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_ref");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_comic_page_chapter");

                    b.HasIndex("ChapterId", "PageNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_comic_page_chapter_number");

                    b.ToTable("page", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.SeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("artist");

                    b.Property<string>("Author")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("author");

                    b.Property<ComicType>("ComicType")
                        .HasColumnType("text")
                        .HasColumnName("comic_type")
                        .HasConversion<string>();

                    b.Property<string>("CoverImageRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_image_ref");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Demographic")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("demographic");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("integer")
                        .HasColumnName("published_year");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publisher");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<ComicStatus>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasConversion<string>();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ComicType")
                        .HasDatabaseName("ix_comic_series_type");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_comic_series_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_comic_series_status");

                    b.ToTable("series", "comic");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.VolumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverImageRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_image_ref");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("date")
                        .HasColumnName("published_date");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<decimal?>("VolumeNumber")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("volume_number");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_comic_volume_series");

                    b.HasIndex("SeriesId", "VolumeNumber")
                        .HasDatabaseName("ix_comic_volume_series_number");

                    b.ToTable("volume", "comic");
                });

            modelBuilder.Entity("CharacterEntityVolumeEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyo.Comic.Postgres.Database.VolumeEntity", null)
                        .WithMany()
                        .HasForeignKey("VolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.AlternateTitleEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("AlternateTitles")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.ChapterEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyo.Comic.Postgres.Database.VolumeEntity", "Volume")
                        .WithMany("Chapters")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.CharacterEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("Characters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.PageEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.ChapterEntity", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.VolumeEntity", b =>
                {
                    b.HasOne("Lyo.Comic.Postgres.Database.SeriesEntity", "Series")
                        .WithMany("Volumes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.SeriesEntity", b =>
                {
                    b.Navigation("AlternateTitles");

                    b.Navigation("Chapters");

                    b.Navigation("Characters");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Lyo.Comic.Postgres.Database.VolumeEntity", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
