<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lyo.Scientific\Lyo.Scientific.csproj"/>
        <ProjectReference Include="..\Lyo.Scientific.Functions\Lyo.Scientific.Functions.fsproj"/>
        <ProjectReference Include="..\..\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
    </ItemGroup>
</Project>
