// <auto-generated />
using System;
using Lyo.Reporting.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Reporting.Postgres.Migrations
{
    [DbContext(typeof(ReportingContext))]
    [Migration("20260720000544_HardenReporting")]
    partial class HardenReporting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DefaultFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_file_name");

                    b.Property<string>("DefaultFormat")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_format");

                    b.Property<string>("DefaultPathPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_path_prefix");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("GenerationProfileKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generation_profile_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("ParameterTypeName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("parameter_type_name");

                    b.Property<string>("ReportDataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_data_json");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_report_definition_created_timestamp");

                    b.HasIndex("GenerationProfileKey")
                        .HasDatabaseName("ix_report_definition_generation_profile_key");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_report_definition_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_report_definition_name");

                    b.ToTable("report_definition", "reporting");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_timestamp");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("OutputFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_file_id");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("text")
                        .HasColumnName("parameters_json");

                    b.Property<string>("PathPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path_prefix");

                    b.Property<string>("ReportDataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_data_json");

                    b.Property<Guid?>("ReportDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_definition_id");

                    b.Property<DateTime?>("StartedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_timestamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_report_generation_created_timestamp");

                    b.HasIndex("OutputFileId")
                        .HasDatabaseName("ix_report_generation_output_file_id");

                    b.HasIndex("ReportDefinitionId")
                        .HasDatabaseName("ix_report_generation_definition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_report_generation_status");

                    b.ToTable("report_generation", "reporting");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGeneration", b =>
                {
                    b.HasOne("Lyo.Reporting.Postgres.Database.ReportDefinition", "ReportDefinition")
                        .WithMany("Generations")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReportDefinition");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportDefinition", b =>
                {
                    b.Navigation("Generations");
                });
#pragma warning restore 612, 618
        }
    }
}
