// <auto-generated />
using System;
using Lyo.Reporting.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Reporting.Postgres.Migrations
{
    [DbContext(typeof(ReportingContext))]
    partial class ReportingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DefaultFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_file_name");

                    b.Property<string>("DefaultFormat")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("default_format");

                    b.Property<string>("DefaultPathPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_path_prefix");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("GenerationProfileKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generation_profile_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("ReportDataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_data_json");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_report_definition_created_timestamp");

                    b.HasIndex("GenerationProfileKey")
                        .HasDatabaseName("ix_report_definition_generation_profile_key");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_report_definition_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_report_definition_name");

                    b.ToTable("report_definition", "reporting");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportDefinitionParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multiple");

                    b.Property<string>("AllowedValues")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allowed_values");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<byte[]>("EncryptedValue")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_value");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_definition_id");

                    b.Property<bool>("Required")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("ValidationRegex")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("validation_regex");

                    b.Property<string>("Value")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_report_definition_parameter");

                    b.HasIndex("ReportDefinitionId")
                        .HasDatabaseName("ix_report_definition_parameter_definition_id");

                    b.HasIndex("ReportDefinitionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_report_definition_parameter_definition_key");

                    b.ToTable("report_definition_parameter", "reporting");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_timestamp");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("format");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("OutputFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_file_id");

                    b.Property<string>("PathPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path_prefix");

                    b.Property<string>("ReportDataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_data_json");

                    b.Property<Guid?>("ReportDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_definition_id");

                    b.Property<DateTime?>("StartedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_timestamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_report_generation_created_timestamp");

                    b.HasIndex("OutputFileId")
                        .HasDatabaseName("ix_report_generation_output_file_id");

                    b.HasIndex("ReportDefinitionId")
                        .HasDatabaseName("ix_report_generation_definition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_report_generation_status");

                    b.ToTable("report_generation", "reporting");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGenerationParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<byte[]>("EncryptedValue")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_value");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<Guid>("ReportGenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_generation_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_report_generation_parameter");

                    b.HasIndex("ReportGenerationId")
                        .HasDatabaseName("ix_report_generation_parameter_generation_id");

                    b.HasIndex("ReportGenerationId", "Key")
                        .HasDatabaseName("ix_report_generation_parameter_generation_key");

                    b.ToTable("report_generation_parameter", "reporting");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportDefinitionParameter", b =>
                {
                    b.HasOne("Lyo.Reporting.Postgres.Database.ReportDefinition", "ReportDefinition")
                        .WithMany("Parameters")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportDefinition");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGeneration", b =>
                {
                    b.HasOne("Lyo.Reporting.Postgres.Database.ReportDefinition", "ReportDefinition")
                        .WithMany("Generations")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReportDefinition");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGenerationParameter", b =>
                {
                    b.HasOne("Lyo.Reporting.Postgres.Database.ReportGeneration", "ReportGeneration")
                        .WithMany("Parameters")
                        .HasForeignKey("ReportGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportGeneration");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportDefinition", b =>
                {
                    b.Navigation("Generations");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Lyo.Reporting.Postgres.Database.ReportGeneration", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
