<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lyo.Validation\Lyo.Validation.csproj"/>
        <ProjectReference Include="..\..\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\..\..\Data\Query\Lyo.Query\Lyo.Query.csproj"/>
        <ProjectReference Include="..\..\..\Data\Query\Lyo.Query.Models\Lyo.Query.Models.csproj"/>
        <ProjectReference Include="..\..\Cache\Lyo.Cache\Lyo.Cache.csproj"/>
    </ItemGroup>

</Project>
