<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Common\Lyo.Common.Json\Lyo.Common.Json.csproj"/>
        <ProjectReference Include="..\Lyo.Validation\Lyo.Validation.csproj"/>
        <ProjectReference Include="..\..\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\..\..\Data\Query\Lyo.Query\Lyo.Query.csproj"/>
        <ProjectReference Include="..\..\..\Data\Query\Lyo.Query.Models\Lyo.Query.Models.csproj"/>
        <ProjectReference Include="..\..\Cache\Lyo.Cache\Lyo.Cache.csproj"/>
    </ItemGroup>

</Project>
