using Lyo.Metrics;
using Lyo.Reporting.Models;
using Lyo.Reporting.Models.Builders;
using Lyo.Reporting.Models.Extensions;
using Lyo.Reporting.Models.Models;

namespace Lyo.Reporting.Web;

/// <summary>Sample reports that show what ReportBuilder can do.</summary>
public static class ReportExamples
{
    /// <summary>Builds a simple sales report with basic sections and columns.</summary>
    public static Report<SalesReportOptions> CreateSalesReport()
    {
        var options = new SalesReportOptions("Q4 2024", DateTime.Now.AddMonths(-3), DateTime.Now, 125000.50m, 45);
        return ReportBuilder<SalesReportOptions>.New(options)
            .SetTitle("Sales Report")
            .SetSubtitle("Quarterly Performance Summary")
            .SetDescription("This report provides an overview of sales performance for the specified period.")
            .AddMetadata("ReportId", Guid.NewGuid())
            .AddMetadata("GeneratedAt", DateTime.Now)
            .AddSection(
                "Summary",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Period", options.Period)
                        .AddCard("Start Date", options.StartDate.ToString("MM/dd/yyyy"))
                        .AddCard("End Date", options.EndDate.ToString("MM/dd/yyyy"))
                        .AddCard("Total Revenue", options.TotalRevenue.ToString("C"), "200px", "right")
                        .AddCard("Total Orders", options.TotalOrders.ToString(), alignment: "right")))
            .AddSection(
                "Revenue Breakdown",
                s => s.AddText("Revenue breakdown by product category:")
                    .AddTable(
                        "Revenue by Category",
                        g => g.AddColumn("Category", "Category")
                            .AddColumn("Revenue", "Revenue", alignment: "right")
                            .AddColumn("Orders", "Orders", alignment: "right")
                            .AddRow("Electronics", "$75,000.00", "25")
                            .AddRow("Clothing", "$30,000.50", "15")
                            .AddRow("Home & Garden", "$20,000.00", "5")))
            .AddSection(
                "Key Metrics",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Average Order Value", (options.TotalRevenue / options.TotalOrders).ToString("C"))
                        .AddCard("Revenue Growth", "+15.3%")
                        .AddCard("Customer Satisfaction", "4.8/5.0")))
            .SetFooter("Generated by Lyo Reporting System")
            .Build();
    }

    /// <summary>Builds an employee performance report with nested sections and grids.</summary>
    public static Report<EmployeePerformanceOptions> CreateEmployeePerformanceReport()
    {
        var options = new EmployeePerformanceOptions("John Doe", "Software Engineer", new(2024, 1, 1), new(2024, 12, 31));
        var projects = new List<ProjectData> {
            new("Project Alpha", 95, 8, new(2024, 2, 1), new(2024, 5, 15)),
            new("Project Beta", 88, 12, new(2024, 6, 1), new(2024, 9, 30)),
            new("Project Gamma", 92, 6, new(2024, 10, 1), new(2024, 12, 31))
        };

        return ReportBuilder<EmployeePerformanceOptions>.New(options)
            .SetTitle("Employee Performance Report")
            .SetSubtitle($"Performance Review: {options.EmployeeName}")
            .AddSection(
                "Employee Information",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Name", options.EmployeeName)
                        .AddCard("Position", options.Position)
                        .AddCard("Review Period", $"{options.StartDate:MM/dd/yyyy} - {options.EndDate:MM/dd/yyyy}")))
            .AddSection(
                "Project Performance",
                s => s.AddText("The following table shows performance metrics for all projects completed during the review period:")
                    .AddTable(
                        "Projects",
                        g => g.SetStriped()
                            .SetBordered()
                            .AddColumn("Project Name", "Name")
                            .AddColumn("Score", "Score", alignment: "right")
                            .AddColumn("Duration (weeks)", "DurationWeeks", alignment: "right")
                            .AddColumn("Start Date", "StartDate")
                            .AddColumn("End Date", "EndDate")
                            .AddRowsFromObjects(
                                projects, p => new object?[] { p.Name, $"{p.Score}%", p.DurationWeeks, p.StartDate.ToString("MM/dd/yyyy"), p.EndDate.ToString("MM/dd/yyyy") })))
            .AddSection(
                "Achievements",
                s => s.AddSubsection(
                        "Technical Skills",
                        sub => sub.AddText("Demonstrated strong technical capabilities:")
                            .AddList("Led implementation of microservices architecture", "Improved code quality metrics by 25%", "Mentored 3 junior developers"))
                    .AddSubsection(
                        "Collaboration",
                        sub => sub.AddText("Excellent collaboration and communication:")
                            .AddNumberedList("Participated in 15+ code reviews", "Presented technical solutions to stakeholders", "Collaborated across 3 different teams")))
            .AddSection(
                "Summary",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Overall Rating", "Exceeds Expectations")
                        .AddCard("Average Project Score", "91.7%")
                        .AddCard("Total Projects", projects.Count.ToString())))
            .SetFooter("Confidential - For Internal Use Only")
            .Build();
    }

    /// <summary>Builds a financial statement report with complex grids and formatting.</summary>
    public static Report<FinancialStatementOptions> CreateFinancialStatementReport()
    {
        var options = new FinancialStatementOptions("Acme Corporation", new(2024, 1, 1), new(2024, 12, 31), 5000000m, 3500000m, 1500000m);
        var expenses = new List<ExpenseItem> {
            new("Salaries & Wages", 2000000m),
            new("Office Rent", 300000m),
            new("Marketing", 500000m),
            new("Utilities", 100000m),
            new("Software Licenses", 200000m),
            new("Other Operating Expenses", 400000m)
        };

        return ReportBuilder<FinancialStatementOptions>.New(options)
            .SetTitle("Financial Statement")
            .SetSubtitle($"{options.CompanyName} - Annual Report")
            .SetDescription($"Financial statement for the period {options.StartDate:yyyy} - {options.EndDate:yyyy}")
            .AddStyle("font-family", "Arial, sans-serif")
            .AddSection(
                "Company Information",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Company Name", options.CompanyName)
                        .AddCard("Fiscal Year", options.StartDate.Year.ToString())
                        .AddCard("Report Period", $"{options.StartDate:MM/dd/yyyy} to {options.EndDate:MM/dd/yyyy}")))
            .AddSection(
                "Income Statement",
                s => s.AddTable(
                    "Revenue & Expenses",
                    g => g.SetTitle("Income Statement")
                        .SetShowHeaders()
                        .SetBordered()
                        .AddColumn("Item", "Item")
                        .AddColumn("Amount", "Amount", alignment: "right", width: "200px")
                        .AddRow("Total Revenue", options.TotalRevenue.ToString("C"))
                        .AddRow("", "")
                        .AddRow("Operating Expenses:", "")
                        .AddRowsFromObjects(expenses, e => new object?[] { $"  {e.Category}", e.Amount.ToString("C") })
                        .AddRow("", "")
                        .AddRow("Total Operating Expenses", options.TotalExpenses.ToString("C"))
                        .AddRow("", "")
                        .AddRow("Net Income", options.NetIncome.ToString("C"))))
            .AddSection(
                "Key Financial Ratios",
                s => s.AddTable(
                    "Ratios",
                    g => g.SetTitle("Financial Ratios")
                        .AddColumn("Ratio", "Ratio")
                        .AddColumn("Value", "Value", alignment: "right")
                        .AddRow("Profit Margin", $"{options.NetIncome / options.TotalRevenue * 100:F2}%")
                        .AddRow("Expense Ratio", $"{options.TotalExpenses / options.TotalRevenue * 100:F2}%")
                        .AddRow("Revenue Growth", "+12.5%")))
            .AddSection(
                "Notes",
                s => s.AddText("This financial statement has been prepared in accordance with generally accepted accounting principles (GAAP).")
                    .AddText("All amounts are expressed in US Dollars."))
            .SetFooter($"Prepared on {DateTime.Now:MMMM dd, yyyy} | Page 1 of 1")
            .Build();
    }

    /// <summary>Builds a project status report with several sections, grids, and content blocks.</summary>
    public static Report<ProjectStatusOptions> CreateProjectStatusReport()
    {
        var options = new ProjectStatusOptions("Website Redesign", "In Progress", 75, new(2024, 1, 15), new(2024, 6, 30));
        var tasks = new List<TaskItem> {
            new("Design Mockups", "Completed", 100, "Alice Johnson"),
            new("Frontend Development", "In Progress", 80, "Bob Smith"),
            new("Backend API", "In Progress", 70, "Charlie Brown"),
            new("Testing", "Not Started", 0, "Diana Prince"),
            new("Deployment", "Not Started", 0, "Eve Wilson")
        };

        return ReportBuilder<ProjectStatusOptions>.New(options)
            .SetTitle("Project Status Report")
            .SetSubtitle($"Project: {options.ProjectName}")
            .AddMetadata("ReportType", "Status")
            .AddMetadata("Priority", "High")
            .AddSection(
                "Project Overview",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Project Name", options.ProjectName)
                        .AddCard("Status", options.Status)
                        .AddCard("Progress", $"{options.Progress}%")
                        .AddCard("Start Date", options.StartDate.ToString("MM/dd/yyyy"))
                        .AddCard("Target Completion", options.TargetDate.ToString("MM/dd/yyyy"))
                        .AddCard("Days Remaining", (options.TargetDate.ToDateTime(TimeOnly.MinValue) - DateTime.Now).Days.ToString())))
            .AddSection(
                "Task Breakdown",
                s => s.AddText("Current status of all project tasks:")
                    .AddTable(
                        "Tasks",
                        g => g.SetTitle("Task Status")
                            .SetStriped()
                            .AddColumn("Task", "TaskName")
                            .AddColumn("Status", "Status")
                            .AddColumn("Progress", "Progress", alignment: "right")
                            .AddColumn("Assigned To", "AssignedTo")
                            .AddRowsFromObjects(tasks, t => new object?[] { t.TaskName, t.Status, $"{t.Progress}%", t.AssignedTo })))
            .AddSection(
                "Milestones",
                s => s.AddSubsection("Completed", sub => sub.AddList("✓ Project kickoff meeting", "✓ Design approval", "✓ Development environment setup"))
                    .AddSubsection(
                        "Upcoming",
                        sub => sub.AddNumberedList("Complete frontend development", "Complete backend API", "Begin testing phase", "Deploy to staging", "Final deployment")))
            .AddSection(
                "Risks & Issues",
                s => s.AddText("Current risks and issues identified:")
                    .AddHtml("<ul><li><strong>Risk:</strong> Potential delay in API completion</li><li><strong>Issue:</strong> Need additional testing resources</li></ul>"))
            .AddSection(
                "Next Steps",
                s => s.AddText("Immediate actions required:")
                    .AddList("Complete backend API by end of week", "Assign additional testing resources", "Schedule deployment planning meeting"))
            .SetFooter($"Report generated on {DateTime.Now:MM/dd/yyyy HH:mm}")
            .Build();
    }

    /// <summary>Builds a metrics dashboard report showing every metric with charts.</summary>
    /// <param name="metrics">Metrics service to visualize</param>
    public static Report<MetricsDashboardOptions> CreateMetricsDashboardReport(IMetrics metrics)
    {
        var options = new MetricsDashboardOptions(DateTime.Now.AddDays(-7), DateTime.Now, "Production");
        return ReportBuilder<MetricsDashboardOptions>.New(options)
            .SetTitle("Metrics Dashboard")
            .SetSubtitle($"Environment: {options.Environment} | Period: {options.StartDate:MM/dd/yyyy} - {options.EndDate:MM/dd/yyyy}")
            .SetDescription("Comprehensive metrics visualization showing system performance and health indicators.")
            .AddMetadata("ReportType", "Metrics")
            .AddMetadata("GeneratedAt", DateTime.Now)
            .AddSection(section => section.AddMetricsDashboard(metrics, "System Metrics Overview"))
            .AddSection(
                "Metrics Summary",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Report Period", $"{options.StartDate:MM/dd/yyyy} to {options.EndDate:MM/dd/yyyy}")
                        .AddCard("Environment", options.Environment)
                        .AddCard("Generated", DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss"))))
            .SetFooter($"Metrics Dashboard Report | Generated on {DateTime.Now:MMMM dd, yyyy 'at' HH:mm}")
            .Build();
    }

    /// <summary>Builds a filtered metrics report showing only specific API-related metrics.</summary>
    /// <param name="metrics">Metrics service to visualize</param>
    public static Report<MetricsDashboardOptions> CreateFilteredMetricsReport(IMetrics metrics)
    {
        var options = new MetricsDashboardOptions(DateTime.Now.AddDays(-1), DateTime.Now, "Production");
        return ReportBuilder<MetricsDashboardOptions>.New(options)
            .SetTitle("API Performance Metrics")
            .SetSubtitle("Filtered View - API Related Metrics Only")
            .SetDescription("This report shows only API-related metrics filtered by prefix and specific metric names.")
            .AddSection(
                "API Request Counters", s => s.AddCounterChartByPrefix(metrics, "api.", "API Request Counters").AddText("These counters track all API-related request metrics."))
            .AddSection(
                "Selected Counters",
                s => s.AddCounterChart(metrics, "Key API Metrics", ["api.requests.total", "api.requests.errors", "api.requests.success"])
                    .AddText("Focus on the most critical API metrics."))
            .AddSection(
                "System Health Gauges",
                s => s.AddGaugeChart(metrics, "System Resource Usage", ["cpu.usage", "memory.usage", "disk.usage"]).AddText("Current system resource utilization."))
            .AddSection(
                "Performance Histograms",
                s => s.AddHistogramChart(metrics, "API Response Times", ["api.response_time", "api.db_query_time"]).AddText("Response time distributions for API operations."))
            .AddSection(
                "High-Value Metrics",
                s => s.AddCounterChartFiltered(metrics, counter => counter.Value > 1000, "High-Value Counters (Value > 1000)").AddText("Counters with values exceeding 1000."))
            .SetFooter($"Filtered Metrics Report | Generated on {DateTime.Now:MM/dd/yyyy}")
            .Build();
    }

    /// <summary>Builds an invoice report with biller/customer info, line items, and totals.</summary>
    public static Report<InvoiceOptions> CreateInvoiceReport()
    {
        var options = new InvoiceOptions(
            "INV-2024-00142", DateTime.Now, DateTime.Now.AddDays(30), new("Acme Corporation", "123 Business St", "New York, NY 10001", "contact@acme.com", "+1 (555) 123-4567"),
            new("Tech Solutions Inc.", "456 Client Ave", "San Francisco, CA 94102", "billing@techsolutions.com"), "Net 30");

        var lineItems = new List<InvoiceLineItem> {
            new("Professional Services - Web Development", 40, 150.00m),
            new("Professional Services - API Integration", 20, 175.00m),
            new("Consulting - Architecture Review", 8, 200.00m),
            new("Software License - Annual", 1, 5000.00m)
        };

        var subtotal = lineItems.Sum(item => item.Quantity * item.UnitPrice);
        var taxRate = 0.08m; // 8% tax
        var taxAmount = subtotal * taxRate;
        var total = subtotal + taxAmount;
        return ReportBuilder<InvoiceOptions>.New(options)
            .SetTitle("INVOICE")
            .SetSubtitle($"Invoice #{options.InvoiceNumber}")
            .AddStyle("font-family", "Arial, sans-serif")
            .AddMetadata("InvoiceNumber", options.InvoiceNumber)
            .AddMetadata("InvoiceDate", options.InvoiceDate)
            .AddSection(
                "Invoice Details",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Invoice Number", options.InvoiceNumber)
                        .AddCard("Invoice Date", options.InvoiceDate.ToString("MM/dd/yyyy"))
                        .AddCard("Due Date", options.DueDate.ToString("MM/dd/yyyy"))
                        .AddCard("Payment Terms", options.PaymentTerms)))
            .AddSection(
                "Biller Information",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Company", options.Biller.CompanyName)
                        .AddCard("Address", options.Biller.Address)
                        .AddCard("City, State ZIP", options.Biller.CityStateZip)
                        .AddCard("Email", options.Biller.Email)
                        .AddCard("Phone", options.Biller.Phone)))
            .AddSection(
                "Bill To",
                s => s.AddGrid(
                    g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                        .AddCard("Company", options.Customer.CompanyName)
                        .AddCard("Address", options.Customer.Address)
                        .AddCard("City, State ZIP", options.Customer.CityStateZip)
                        .AddCard("Email", options.Customer.Email)))
            .AddSection(
                "Line Items",
                s => s.AddTable(
                    "Items",
                    g => g.SetTitle("Invoice Line Items")
                        .SetShowHeaders()
                        .SetBordered()
                        .SetStriped()
                        .AddColumn("Description", "Description", "400px")
                        .AddColumn("Quantity", "Quantity", alignment: "right", width: "100px")
                        .AddColumn("Unit Price", "UnitPrice", alignment: "right", width: "120px")
                        .AddColumn("Amount", "Amount", alignment: "right", width: "120px")
                        .AddRowsFromObjects(
                            lineItems,
                            item => new object?[] { item.Description, item.Quantity.ToString(), item.UnitPrice.ToString("C"), (item.Quantity * item.UnitPrice).ToString("C") })))
            .AddSection(
                "Totals",
                s => s.AddTable(
                    "Summary",
                    g => g.SetShowHeaders(false)
                        .SetBordered()
                        .AddColumn("Label", "Label", alignment: "right", width: "200px")
                        .AddColumn("Amount", "Amount", alignment: "right", width: "200px")
                        .AddRow("Subtotal:", subtotal.ToString("C"))
                        .AddRow($"Tax ({taxRate:P0}):", taxAmount.ToString("C"))
                        .AddRow("", "")
                        .AddRow("Total Due:", total.ToString("C"))))
            .AddSection(
                "Payment Instructions",
                s => s.AddText("Payment Terms: " + options.PaymentTerms)
                    .AddText("Please remit payment by the due date to avoid late fees.")
                    .AddList(
                        "Payment can be made via bank transfer, check, or credit card", "Bank transfer details: Account #123456789, Routing #987654321",
                        "For questions about this invoice, please contact billing@acme.com"))
            .SetFooter($"Thank you for your business! | Invoice generated on {DateTime.Now:MMMM dd, yyyy}")
            .Build();
    }

    // Record types used by the examples
    public sealed record SalesReportOptions(string Period, DateTime StartDate, DateTime EndDate, decimal TotalRevenue, int TotalOrders);

    public sealed record EmployeePerformanceOptions(string EmployeeName, string Position, DateOnly StartDate, DateOnly EndDate);

    public sealed record ProjectData(string Name, int Score, int DurationWeeks, DateOnly StartDate, DateOnly EndDate);

    public sealed record FinancialStatementOptions(string CompanyName, DateOnly StartDate, DateOnly EndDate, decimal TotalRevenue, decimal TotalExpenses, decimal NetIncome);

    public sealed record ExpenseItem(string Category, decimal Amount);

    public sealed record ProjectStatusOptions(string ProjectName, string Status, int Progress, DateOnly StartDate, DateOnly TargetDate);

    public sealed record TaskItem(string TaskName, string Status, int Progress, string AssignedTo);

    public sealed record MetricsDashboardOptions(DateTime StartDate, DateTime EndDate, string Environment);

    public sealed record InvoiceOptions(string InvoiceNumber, DateTime InvoiceDate, DateTime DueDate, BillerInfo Biller, CustomerInfo Customer, string PaymentTerms);

    public sealed record BillerInfo(string CompanyName, string Address, string CityStateZip, string Email, string Phone);

    public sealed record CustomerInfo(string CompanyName, string Address, string CityStateZip, string Email);

    public sealed record InvoiceLineItem(string Description, int Quantity, decimal UnitPrice);
}