using Lyo.Common.Metadata.Records;
using Lyo.Exceptions;
using Lyo.Reporting.Models.Builders;
using Lyo.Reporting.Models.Controls;
using Lyo.Reporting.Models.Enums;
using Lyo.Reporting.Models.Models;
using Lyo.Reporting.Models.Request;

namespace Lyo.Reporting.Models.Composition;

/// <summary>Named starter composition for the designer Templates menu and Test Gateway seed.</summary>
/// <param name="Name">Definition and menu label.</param>
/// <param name="Description">Short purpose copied onto the seeded definition.</param>
/// <param name="Create">Factory that returns a new composition graph.</param>
public sealed record ReportDesignSample(string Name, string Description, Func<Report<object>> Create)
{
    /// <summary>Builds a create-definition request, copying example parameter JSON onto <c>Value</c> so generate has sample rows.</summary>
    public ReportDefinitionReq ToDefinitionReq(ReportFormat? defaultFormat = ReportFormat.Html)
        => ReportDesignTemplates.ToDefinitionReq(Name, Description, Create(), defaultFormat);
}

/// <summary>Starter compositions for the design workbench. Placeholders such as <c>{Period}</c> bind from example parameter values.</summary>
public static class ReportDesignTemplates
{
    private static readonly string JsonArrayType = LyoTypeInfo.JsonArray.FullName;

    private const string SampleLineItems = """[{"item":"Widget A","qty":2,"amount":40},{"item":"Widget B","qty":1,"amount":18.5}]""";
    private const string SampleRegionSeries = """[{"label":"North","value":12},{"label":"South","value":8},{"label":"West","value":15}]""";

    /// <summary>
    /// Saved-definition samples (excludes <see cref="Blank" />). Used by the workbench Templates menu and Test Gateway seed.
    /// Each call to <see cref="ReportDesignSample.Create" /> returns a new graph.
    /// </summary>
    public static IReadOnlyList<ReportDesignSample> Samples { get; } = [
        new("Controls gallery", "Kitchen sink: TOC, charts, FromParameter series, page break, collapsed appendix.", ControlsGallery),
        new("Sales summary", "KPI cards plus a static category chart.", SalesSummary),
        new("Invoice", "Bill-to, FromParameter line items, totals, page break, and signature.", Invoice),
        new("Operations dashboard", "KPI cards, FromParameter bar chart, sparkline/gauge, collapsed notes.", OperationsDashboard)
    ];

    /// <summary>Blank report with one empty section, ready for the designer.</summary>
    public static Report<object> Blank()
        => ReportBuilder<object>.New()
            .SetTitle("Untitled report")
            .SetSubtitle("Designed in the report workbench")
            .SetLayout(l => l.SetTheme("Default").SetPageSize("Letter").SetOrientation("Portrait").SetAccentColor("#2563eb"))
            .AddSection("Summary", s => s.AddText("Replace this text. Use {Placeholders} that match parameter keys."))
            .SetFooter("Generated by Lyo Reporting")
            .Build();

    /// <summary>Kitchen-sink sample that exercises the new controls plus example parameters.</summary>
    public static Report<object> ControlsGallery()
        => ReportBuilder<object>.New()
            .SetTitle("{ReportTitle}")
            .SetSubtitle("{Period} · {Customer}")
            .SetDescription("Preview this gallery with the example parameters on the Parameters tab. Hidden callouts use VisibleWhen.")
            .SetLayout(
                l => l.SetTheme("Default")
                    .SetPageSize("Letter")
                    .SetOrientation("Portrait")
                    .SetAccentColor("#2563eb")
                    .SetHeaderText("{Customer}")
                    .SetWatermark("{Watermark}")
                    .ShowPageNumbers())
            .AddParameter("ReportTitle", example: "\"Q4 Performance\"", description: "Report title")
            .AddParameter("Period", example: "\"Q4 2024\"", required: true, description: "Reporting period")
            .AddParameter("Customer", example: "\"Acme Corporation\"", required: true)
            .AddParameter("Completion", type: "System.Int32", example: "72", description: "Progress percent")
            .AddParameter("ShowRisks", type: "System.Boolean", example: "true", description: "When true, the risks callout is shown")
            .AddParameter("Watermark", example: "\"DRAFT\"")
            .AddParameter("RegionSeries", type: JsonArrayType, example: SampleRegionSeries, description: "JSON array of {label,value} for the FromParameter chart")
            .AddSection(
                "Overview",
                s => s.SetId("overview")
                    .AddTableOfContents()
                    .AddBadge("Draft", "warning")
                    .AddBadge("On track", "success")
                    .AddGrid(
                        g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                            .AddCard("Period", "{Period}")
                            .AddCard("Customer", "{Customer}", emphasized: true)
                            .AddCard("Completion", "{Completion}%", alignment: "right"))
                    .AddHeading("Highlights", 3)
                    .AddText("Revenue and delivery for {Period}.")
                    .AddCallout("All figures are example values from the workbench, not a live generate.", "info")
                    .AddProgress(72, "Completion")
                    .AddKeyValue("Account manager", "Jordan Lee")
                    .AddKeyValue("Status", "On track"))
            .AddSection(
                "Delivery",
                s => s.SetId("delivery")
                    .AddTable(
                        "Milestones",
                        g => g.SetStriped()
                            .SetBordered()
                            .SetShowRowNumbers()
                            .AddColumn("Milestone", "Name")
                            .AddColumn("Owner", "Owner")
                            .AddColumn("Status", "Status")
                            .AddRow("Discovery", "Alex", "Done")
                            .AddRow("Build", "Sam", "In progress")
                            .AddRow("Launch", "Riley", "Queued"))
                    .AddDivider()
                    .AddQuote("Ship the smallest thing that proves the design.")
                    .AddCode("ReportBuilder<object>.New().SetTitle(\"{ReportTitle}\")")
                    .AddList("Bind placeholders from example params", "Save as a definition when the layout is right", "Generate HTML/PDF from TestApi to confirm renderers")
                    .AddTimeline(["Discovery|Kickoff complete", "Build|In progress", "Launch|Queued"]))
            .AddSection(
                "Charts",
                s => s.SetId("charts")
                    .AddChart(ChartKind.Bar, "Static series", ["North|12", "South|8", "West|15"])
                    .AddChartFromParameter(ChartKind.Bar, "RegionSeries", "From example parameter")
                    .AddChart(ChartKind.Sparkline, "Weekly trend", ["W1|4", "W2|7", "W3|6", "W4|9"], height: 80)
                    .AddChart(ChartKind.Gauge, "Completion", ["Done|72", "Remaining|28"], height: 180)
                    .AddHtml("<p>HTML block with <strong>emphasis</strong> for the gallery.</p>"))
            .AddSection(
                "Risks",
                s => s.SetVisibleWhen("ShowRisks=true")
                    .AddCallout("API completion may slip if example params stay on Draft watermark.", "warning")
                    .AddNumberedList("Confirm owner for Launch", "Replace example grid rows with a data provider", "Turn off the watermark before sending"))
            .AddSection(
                "Billing",
                s => s.AddAddress("Bill to", ["{Customer}", "100 Main Street", "Springfield, ST 00000"])
                    .AddTotals(["Subtotal|$100.00", "Tax|$8.00", "Total|$108.00"])
                    .AddCheckbox(["I agree to the terms", "Net 30 payment"], "Please confirm:")
                    .AddNotes("Leave packages at the loading dock.", "Notes")
                    .AddPageBreak()
                    .AddSignature("Authorized by", "Jordan Lee"))
            .AddSection(
                "Appendix",
                s => s.SetCollapsed()
                    .AddHeading("Methodology", 3)
                    .AddText("Collapsed in generate output; dimmed on the design canvas so you can still edit it."))
            .SetFooter("Workbench preview for {Customer} · {Period}")
            .Build();

    /// <summary>Sales-style summary that maps cleanly onto definition parameters.</summary>
    public static Report<object> SalesSummary()
        => ReportBuilder<object>.New()
            .SetTitle("Sales report")
            .SetSubtitle("{Period}")
            .SetLayout(l => l.SetAccentColor("#0f766e").SetTheme("Formal").SetPageSize("Letter"))
            .AddParameter("Period", example: "\"Q4 2024\"", required: true)
            .AddParameter("Revenue", example: "\"$125,000.50\"")
            .AddParameter("Orders", type: "System.Int32", example: "45")
            .AddSection(
                "Summary",
                s => s.AddTableOfContents()
                    .AddGrid(
                        g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                            .AddCard("Period", "{Period}")
                            .AddCard("Total revenue", "{Revenue}", alignment: "right")
                            .AddCard("Orders", "{Orders}", alignment: "right"))
                    .AddText("Use example parameters to see how this header binds before you generate."))
            .AddSection(
                "Breakdown",
                s => s.AddTable(
                        "Revenue by category",
                        g => g.SetBordered()
                            .SetStriped()
                            .AddColumn("Category")
                            .AddColumn("Revenue", alignment: "right")
                            .AddColumn("Orders", alignment: "right")
                            .AddRow("Electronics", "$75,000.00", "25")
                            .AddRow("Clothing", "$30,000.50", "15")
                            .AddRow("Home & Garden", "$20,000.00", "5"))
                    .AddChart(ChartKind.Bar, "Revenue by category", ["Electronics|75000", "Clothing|30000.50", "Home & Garden|20000"]))
            .SetFooter("Lyo Reporting")
            .Build();

    /// <summary>Invoice-style composition: FromParameter line items, totals, page break, and signature.</summary>
    public static Report<object> Invoice()
        => ReportBuilder<object>.New()
            .SetTitle("Invoice {InvoiceNo}")
            .SetSubtitle("{Period} · {Customer}")
            .SetDescription("Line items bind from the LineItems JSON array parameter. Preview uses the example rows without mutating the grid.")
            .SetLayout(
                l => l.SetTheme("Formal")
                    .SetPageSize("Letter")
                    .SetOrientation("Portrait")
                    .SetAccentColor("#1e3a5f")
                    .SetHeaderText("Invoice {InvoiceNo}")
                    .ShowPageNumbers())
            .AddParameter("InvoiceNo", example: "\"INV-1042\"", required: true, description: "Invoice number")
            .AddParameter("Period", example: "\"Q4 2024\"", required: true)
            .AddParameter("Customer", example: "\"Acme Corporation\"", required: true)
            .AddParameter("LineItems", type: JsonArrayType, example: SampleLineItems, required: true, description: "JSON array of {item,qty,amount}")
            .AddSection(
                "Invoice",
                s => s.SetId("invoice")
                    .AddTableOfContents()
                    .AddGrid(
                        g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                            .AddCard("Invoice", "{InvoiceNo}", emphasized: true)
                            .AddCard("Period", "{Period}")
                            .AddCard("Customer", "{Customer}"))
                    .AddAddress("Bill to", ["{Customer}", "100 Main Street", "Springfield, ST 00000"])
                    .AddTable(
                        "Line items",
                        g => g.SetBordered()
                            .SetStriped()
                            .SetShowRowNumbers()
                            .SetFromParameter("LineItems")
                            .AddColumn("Item", "item")
                            .AddColumn("Qty", "qty", alignment: "right")
                            .AddColumn("Amount", "amount", alignment: "right"))
                    .AddTotals(["Subtotal|$58.50", "Tax|$4.68", "Total|$63.18"])
                    .AddPageBreak()
                    .AddCheckbox(["I agree to the terms", "Net 30 payment"], "Please confirm:")
                    .AddNotes("Remit to the lockbox on the statement. PO must appear on the wire memo.", "Payment")
                    .AddSignature("Authorized by", "Jordan Lee"))
            .SetFooter("Invoice {InvoiceNo} · {Customer}")
            .Build();

    /// <summary>Operations-style dashboard: KPI cards, FromParameter chart, sparkline/gauge, collapsed methodology.</summary>
    public static Report<object> OperationsDashboard()
        => ReportBuilder<object>.New()
            .SetTitle("Operations · {Period}")
            .SetSubtitle("{Region}")
            .SetDescription("KPI cards plus a chart filled from the RegionSeries example JSON at paint time.")
            .SetLayout(
                l => l.SetTheme("Default")
                    .SetPageSize("Letter")
                    .SetOrientation("Landscape")
                    .SetAccentColor("#0f766e")
                    .ShowPageNumbers())
            .AddParameter("Period", example: "\"Q4 2024\"", required: true)
            .AddParameter("Region", example: "\"Americas\"")
            .AddParameter("Revenue", example: "\"$125,000.50\"")
            .AddParameter("Orders", type: "System.Int32", example: "45")
            .AddParameter("OnTime", type: "System.Int32", example: "94", description: "On-time percent")
            .AddParameter("RegionSeries", type: JsonArrayType, example: SampleRegionSeries, description: "JSON array of {label,value}")
            .AddSection(
                "Snapshot",
                s => s.SetId("snapshot")
                    .AddTableOfContents()
                    .AddGrid(
                        g => g.SetTemplateColumns("repeat(auto-fit, minmax(220px, 1fr))")
                            .AddCard("Period", "{Period}")
                            .AddCard("Region", "{Region}", emphasized: true)
                            .AddCard("Revenue", "{Revenue}", alignment: "right")
                            .AddCard("Orders", "{Orders}", alignment: "right")
                            .AddCard("On-time", "{OnTime}%", alignment: "right"))
                    .AddChartFromParameter(ChartKind.Bar, "RegionSeries", "Orders by region")
                    .AddChart(ChartKind.Sparkline, "Weekly volume", ["W1|38", "W2|41", "W3|39", "W4|45"], height: 80)
                    .AddChart(ChartKind.Gauge, "On-time", ["On time|94", "Late|6"], height: 180)
                    .AddBadge("Healthy", "success"))
            .AddSection(
                "Methodology",
                s => s.SetCollapsed()
                    .AddHeading("Notes", 3)
                    .AddText("Collapsed in generate output. On the canvas this section stays visible and dimmed so you can still edit it.")
                    .AddCallout("Replace RegionSeries example JSON with a live parameter when you wire a data provider.", "info"))
            .SetFooter("Operations dashboard · {Period}")
            .Build();

    /// <summary>Builds a create-definition request from an already-built composition, copying example parameter JSON onto <c>Value</c>.</summary>
    public static ReportDefinitionReq ToDefinitionReq(string name, string? description, Report<object> report, ReportFormat? defaultFormat = ReportFormat.Html)
    {
        ArgumentHelpers.ThrowIfNullOrWhiteSpace(name);
        ArgumentHelpers.ThrowIfNull(report);
        return new() {
            Name = name.Trim(),
            Description = description,
            ReportDataJson = ReportJson.Serialize(report),
            IsActive = true,
            DefaultFormat = defaultFormat,
            CreateParameters = report.ParameterSpecs
                .Where(s => !string.IsNullOrWhiteSpace(s.Key))
                .Select(
                    s => new ReportDefinitionParameterReq {
                        Key = s.Key.Trim(),
                        Type = s.Type,
                        Value = s.DefaultValue ?? s.ExampleValue,
                        Description = s.Description,
                        Required = s.Required,
                        AllowedValues = s.AllowedValues
                    })
                .ToList()
        };
    }
}
