<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Benchmark\Lyo.Benchmarking\Lyo.Benchmarking.csproj"/>
        <ProjectReference Include="..\Lyo.Compression\Lyo.Compression.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.BZip2\Lyo.Compression.BZip2.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.LZ4\Lyo.Compression.LZ4.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.LZMA\Lyo.Compression.LZMA.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Snappier\Lyo.Compression.Snappier.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.XZ\Lyo.Compression.XZ.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Zstd\Lyo.Compression.Zstd.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8"/>
    </ItemGroup>

</Project>

