<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Benchmark\Lyo.Benchmark\Lyo.Benchmark.csproj"/>
        <ProjectReference Include="..\..\..\Core\Streams\Lyo.Streams\Lyo.Streams.csproj"/>
        <ProjectReference Include="..\Lyo.Compression\Lyo.Compression.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.BZip2\Lyo.Compression.BZip2.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Lz4\Lyo.Compression.Lz4.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Lzma\Lyo.Compression.Lzma.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Snappier\Lyo.Compression.Snappier.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Xz\Lyo.Compression.Xz.csproj"/>
        <ProjectReference Include="..\Lyo.Compression.Zstd\Lyo.Compression.Zstd.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
    </ItemGroup>

</Project>

