// <auto-generated />
using System;
using Lyo.HomeInventory.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.HomeInventory.Postgres.Migrations
{
    [DbContext(typeof(HomeInventoryDbContext))]
    partial class HomeInventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("home_inventory")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_home_inv_category_parent");

                    b.HasIndex("Name", "ParentCategoryId")
                        .HasDatabaseName("ix_home_inv_category_name_parent");

                    b.ToTable("category", "home_inventory");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcquiredDate")
                        .HasColumnType("date")
                        .HasColumnName("acquired_date");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("batch_number");

                    b.Property<string>("BluetoothMacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bluetooth_mac_address");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Color")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("color");

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("condition");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cost");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_of_origin");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomAttributesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_attributes_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Ean")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ean");

                    b.Property<string>("EthernetMacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ethernet_mac_address");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<string>("Imei")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("imei");

                    b.Property<string>("Isbn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("isbn");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lot_number");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer_part_number");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_number");

                    b.Property<decimal?>("Msrp")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("msrp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_entity_id");

                    b.Property<string>("OwnerEntityType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_entity_type");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_item_id");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("purchase_order_number");

                    b.Property<string>("SalesOrderNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sales_order_number");

                    b.Property<string>("Seller")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("seller");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Sku")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sku");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Upc")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("upc");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("VendorSku")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("vendor_sku");

                    b.Property<DateTime?>("WarrantyExpires")
                        .HasColumnType("date")
                        .HasColumnName("warranty_expires");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("integer")
                        .HasColumnName("weight_grams");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.Property<string>("WifiMacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wifi_mac_address");

                    b.HasKey("Id");

                    b.HasIndex("BluetoothMacAddress")
                        .HasDatabaseName("ix_home_inv_item_bt_mac");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_home_inv_item_category");

                    b.HasIndex("EthernetMacAddress")
                        .HasDatabaseName("ix_home_inv_item_eth_mac");

                    b.HasIndex("Imei")
                        .HasDatabaseName("ix_home_inv_item_imei");

                    b.HasIndex("ParentItemId")
                        .HasDatabaseName("ix_home_inv_item_parent");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_home_inv_item_serial");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_home_inv_item_sku")
                        .HasFilter("sku IS NOT NULL");

                    b.HasIndex("OwnerEntityType", "OwnerEntityId")
                        .HasDatabaseName("ix_home_inv_item_owner");

                    b.ToTable("item", "home_inventory");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_location_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_home_inv_location_code");

                    b.HasIndex("ParentLocationId")
                        .HasDatabaseName("ix_home_inv_location_parent");

                    b.ToTable("location", "home_inventory");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedByEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_entity_id");

                    b.Property<string>("CreatedByEntityType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_entity_type");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer")
                        .HasColumnName("movement_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_number");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_home_inv_movement_created");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_home_inv_movement_item");

                    b.HasIndex("ToLocationId");

                    b.ToTable("movement", "home_inventory");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemStockEntity", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity_on_hand");

                    b.Property<decimal>("QuantityReserved")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity_reserved");

                    b.Property<decimal?>("ReorderPoint")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("reorder_point");

                    b.Property<DateTime>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("ItemId", "LocationId");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_home_inv_stock_location");

                    b.ToTable("stock", "home_inventory");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeCategoryEntity", b =>
                {
                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeCategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemEntity", b =>
                {
                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeCategoryEntity", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeItemEntity", "ParentItem")
                        .WithMany("ChildItems")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", b =>
                {
                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemMovementEntity", b =>
                {
                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", "FromLocation")
                        .WithMany("MovementsFrom")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeItemEntity", "Item")
                        .WithMany("Movements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", "ToLocation")
                        .WithMany("MovementsTo")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromLocation");

                    b.Navigation("Item");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemStockEntity", b =>
                {
                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeItemEntity", "Item")
                        .WithMany("StockRows")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", "Location")
                        .WithMany("StockRows")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeCategoryEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeItemEntity", b =>
                {
                    b.Navigation("ChildItems");

                    b.Navigation("Movements");

                    b.Navigation("StockRows");
                });

            modelBuilder.Entity("Lyo.HomeInventory.Postgres.Database.HomeLocationEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MovementsFrom");

                    b.Navigation("MovementsTo");

                    b.Navigation("StockRows");
                });
#pragma warning restore 612, 618
        }
    }
}
