// <auto-generated />
using System;
using Lyo.Comment.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Comment.Postgres.Migrations
{
    [DbContext(typeof(CommentDbContext))]
    [Migration("20260510032212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("comment")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Comment.Postgres.Database.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("content");

                    b.Property<string>("Context")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("DeletedByType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deleted_by_type");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("dislike_count");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ForEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_type");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_type");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("like_count");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("ReplyToCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_comment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("private")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_comment_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_comment_expires_at")
                        .HasFilter("\"expires_at\" IS NOT NULL");

                    b.HasIndex("ReplyToCommentId")
                        .HasDatabaseName("ix_comment_reply_to");

                    b.HasIndex("TenantId", "Context")
                        .HasDatabaseName("ix_comment_tenant_context");

                    b.HasIndex("TenantId", "ForEntityType", "ForEntityId")
                        .HasDatabaseName("ix_comment_tenant_for_entity");

                    b.HasIndex("TenantId", "FromEntityType", "FromEntityId")
                        .HasDatabaseName("ix_comment_tenant_from_entity");

                    b.ToTable("comment", "comment");
                });

            modelBuilder.Entity("Lyo.Comment.Postgres.Database.CommentReactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<Guid>("ForEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_type");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("FromEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_entity_type");

                    b.Property<int>("ReactionType")
                        .HasColumnType("integer")
                        .HasColumnName("reaction_type");

                    b.HasKey("Id");

                    b.HasIndex("ForEntityType", "ForEntityId")
                        .HasDatabaseName("ix_comment_reaction_for_entity");

                    b.HasIndex("ForEntityType", "ForEntityId", "FromEntityType", "FromEntityId")
                        .IsUnique()
                        .HasDatabaseName("ix_comment_reaction_for_from");

                    b.ToTable("comment_reaction", "comment");
                });
#pragma warning restore 612, 618
        }
    }
}
