// <auto-generated />
using System;
using Lyo.Authentication.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Authentication.Postgres.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260526192802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.LinkedIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailAtLink")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_at_link");

                    b.Property<DateTime?>("LastUsedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_timestamp");

                    b.Property<DateTime>("LinkedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_timestamp");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("RawClaimsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_claims_json");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes_json");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UnlinkedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlinked_timestamp");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_linked_identity_provider");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_linked_identity_tenant_id")
                        .HasFilter("\"tenant_id\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_linked_identity_user_id");

                    b.HasIndex("TenantId", "Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_linked_identity_tenant_provider_subject")
                        .HasFilter("\"unlinked_timestamp\" IS NULL");

                    b.ToTable("linked_identity", "user");
                });

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.TokenEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("ExpiresTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_timestamp");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastUsedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_timestamp");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTime?>("RevokedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_timestamp");

                    b.Property<string>("Ring")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ring");

                    b.Property<string>("RotatedFromId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("rotated_from_id");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes_json");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresTimestamp")
                        .HasDatabaseName("ix_token_expires_timestamp")
                        .HasFilter("\"expires_timestamp\" IS NOT NULL");

                    b.HasIndex("RotatedFromId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_token_tenant_id")
                        .HasFilter("\"tenant_id\" IS NOT NULL");

                    b.HasIndex("Kind", "Ring")
                        .HasDatabaseName("ix_token_kind_ring");

                    b.HasIndex("UserId", "RevokedTimestamp")
                        .HasDatabaseName("ix_token_user_id_revoked_timestamp");

                    b.ToTable("token", "user");
                });

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disabled_reason");

                    b.Property<DateTime?>("DisabledTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_timestamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<DateTime?>("LastLoginTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_timestamp");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PreferredLanguageBcp47")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_language_bcp47");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes_json");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DisabledTimestamp")
                        .HasDatabaseName("ix_user_disabled_timestamp")
                        .HasFilter("\"disabled_timestamp\" IS NULL");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_user_tenant_email");

                    b.HasIndex("LastLoginTimestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_user_last_login_timestamp");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_user_person_id")
                        .HasFilter("\"person_id\" IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenant_id")
                        .HasFilter("\"tenant_id\" IS NOT NULL");

                    b.ToTable("user", "user");
                });

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.UserEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_user_event_kind");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_event_tenant_id")
                        .HasFilter("\"tenant_id\" IS NOT NULL");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_user_event_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_event_user_id")
                        .HasFilter("\"user_id\" IS NOT NULL");

                    b.ToTable("event", "user");
                });

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.LinkedIdentityEntity", b =>
                {
                    b.HasOne("Lyo.Authentication.Postgres.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.TokenEntity", b =>
                {
                    b.HasOne("Lyo.Authentication.Postgres.Database.TokenEntity", null)
                        .WithMany()
                        .HasForeignKey("RotatedFromId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lyo.Authentication.Postgres.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Lyo.Authentication.Postgres.Database.UserEventEntity", b =>
                {
                    b.HasOne("Lyo.Authentication.Postgres.Database.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
