// <auto-generated />
using System;
using Lyo.FileSystemWatcher.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.FileSystemWatcher.Postgres.Migrations
{
    [DbContext(typeof(FileSystemWatcherDbContext))]
    partial class FileSystemWatcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("filesystem_watcher")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemChangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("change_json");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("change_type");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_directory");

                    b.Property<string>("NewPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("new_path");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OldPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("old_path");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_id");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("WatchId", "OccurredAtUtc")
                        .HasDatabaseName("ix_filesystem_watcher_change_watch_occurred");

                    b.ToTable("change", "filesystem_watcher");
                });

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentHashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_hash_algorithm");

                    b.Property<int>("DirectoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("directory_count");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at_utc");

                    b.Property<string>("TreeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tree_json");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_id");

                    b.HasKey("Id");

                    b.HasIndex("WatchId", "ContentHashAlgorithm", "ContentHash")
                        .HasDatabaseName("ix_filesystem_watcher_snapshot_watch_hash");

                    b.HasIndex("WatchId", "TakenAtUtc")
                        .HasDatabaseName("ix_filesystem_watcher_snapshot_watch_taken");

                    b.ToTable("snapshot", "filesystem_watcher");
                });

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemWatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("root_path");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .HasDatabaseName("ix_filesystem_watcher_watch_root");

                    b.ToTable("watch", "filesystem_watcher");
                });

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemChangeEntity", b =>
                {
                    b.HasOne("Lyo.FileSystemWatcher.Postgres.Database.FileSystemSnapshotEntity", "Snapshot")
                        .WithMany("Changes")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lyo.FileSystemWatcher.Postgres.Database.FileSystemWatchEntity", "Watch")
                        .WithMany("Changes")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemSnapshotEntity", b =>
                {
                    b.HasOne("Lyo.FileSystemWatcher.Postgres.Database.FileSystemWatchEntity", "Watch")
                        .WithMany("Snapshots")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemSnapshotEntity", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Lyo.FileSystemWatcher.Postgres.Database.FileSystemWatchEntity", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
