// <auto-generated />
using System;
using Lyo.ShortUrl.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.ShortUrl.Postgres.Migrations
{
    [DbContext(typeof(ShortUrlDbContext))]
    partial class ShortUrlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("url")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.ShortUrl.Postgres.Database.ShortUrlEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<long>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("click_count");

                    b.Property<string>("CustomAlias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custom_alias");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastAccessedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_date");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("long_url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_short_urls_created_timestamp");

                    b.HasIndex("CustomAlias")
                        .IsUnique()
                        .HasDatabaseName("ix_short_urls_custom_alias")
                        .HasFilter("custom_alias IS NOT NULL");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("ix_short_urls_expiration_date");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_short_urls_is_active");

                    b.HasIndex("IsActive", "ExpirationDate")
                        .HasDatabaseName("ix_short_urls_is_active_expiration_date");

                    b.ToTable("short_urls", "url");
                });

            modelBuilder.Entity("Lyo.ShortUrl.Postgres.Database.UrlClickEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("referrer");

                    b.Property<string>("ShortUrlId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_url_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ClickedAt")
                        .HasDatabaseName("ix_url_clicks_clicked_at");

                    b.HasIndex("ShortUrlId")
                        .HasDatabaseName("ix_url_clicks_short_url_id");

                    b.HasIndex("ShortUrlId", "ClickedAt")
                        .HasDatabaseName("ix_url_clicks_short_url_id_clicked_at");

                    b.ToTable("url_clicks", "url");

                    b.HasOne("Lyo.ShortUrl.Postgres.Database.ShortUrlEntity", "ShortUrl")
                        .WithMany("Clicks")
                        .HasForeignKey("ShortUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortUrl");
                });

            modelBuilder.Entity("Lyo.ShortUrl.Postgres.Database.ShortUrlEntity", b =>
                {
                    b.Navigation("Clicks");
                });
#pragma warning restore 612, 618
        }
    }
}

