<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Benchmark\Lyo.Benchmarking\Lyo.Benchmarking.csproj"/>
        <ProjectReference Include="..\Lyo.Encryption\Lyo.Encryption.csproj"/>
        <ProjectReference Include="..\Lyo.Encryption.AesCcm\Lyo.Encryption.AesCcm.csproj"/>
        <ProjectReference Include="..\Lyo.Encryption.AesSiv\Lyo.Encryption.AesSiv.csproj"/>
        <ProjectReference Include="..\Lyo.Encryption.XChaCha20Poly1305\Lyo.Encryption.XChaCha20Poly1305.csproj"/>
        <ProjectReference Include="..\Lyo.Keystore\Lyo.Keystore.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
    </ItemGroup>

</Project>

