// <auto-generated />
using System;
using Lyo.Geolocation.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Lyo.Geolocation.Postgres.Migrations
{
    [DbContext(typeof(GeolocationDbContext))]
    [Migration("20260528182407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geolocation")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Geolocation.Postgres.Database.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BldgCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bldg_code");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<NpgsqlPoint?>("Coordinates")
                        .HasColumnType("point")
                        .HasColumnName("coordinates");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("county");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<DateOnly?>("FirstReportedDate")
                        .HasColumnType("date")
                        .HasColumnName("first_reported_date");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_address");

                    b.Property<double?>("GeocodeConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("geocode_confidence");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("house_number");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool?>("IsDeliverable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deliverable");

                    b.Property<bool?>("IsMergedAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_merged_address");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateOnly?>("LastReportedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_reported_date");

                    b.Property<DateTime?>("LocallyModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locally_modified_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("PropertyIndicator")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("property_indicator");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("province");

                    b.Property<DateOnly?>("PublicFirstSeenDate")
                        .HasColumnType("date")
                        .HasColumnName("public_first_seen_date");

                    b.Property<string>("SourceEntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_entity_type");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street_address");

                    b.Property<string>("StreetAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street_address_line2");

                    b.Property<string>("StreetName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("street_name");

                    b.Property<string>("StreetPostDirection")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("street_post_direction");

                    b.Property<string>("StreetPreDirection")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("street_pre_direction");

                    b.Property<string>("StreetType")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("street_type");

                    b.Property<string>("SubAdministrativeArea")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_administrative_area");

                    b.Property<string>("SubLocality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_locality");

                    b.Property<string>("Unit")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("unit");

                    b.Property<int?>("UnitCount")
                        .HasColumnType("integer")
                        .HasColumnName("unit_count");

                    b.Property<string>("UnitType")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("unit_type");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("UtilityCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("utility_code");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("zipcode");

                    b.Property<string>("Zipcode4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("zipcode4");

                    b.HasKey("Id");

                    b.HasIndex("SourceEntityType", "SourceEntityId")
                        .IsUnique()
                        .HasDatabaseName("uq_address_source")
                        .HasFilter("\"source_entity_type\" IS NOT NULL AND \"source_entity_id\" IS NOT NULL");

                    b.ToTable("address", "geolocation");
                });
#pragma warning restore 612, 618
        }
    }
}
