<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Description>PostgreSQL implementation of Lyo.ShortUrl using Entity Framework Core.</Description>
        <PackageTags>url shortener postgres postgresql entityframework ef</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Data\Postgres\Lyo.Postgres\Lyo.Postgres.csproj"/>
        <ProjectReference Include="..\Lyo.ShortUrl\Lyo.ShortUrl.csproj"/>
        <ProjectReference Include="..\..\..\Core\Lyo.Exceptions\Lyo.Exceptions.csproj"/>
    </ItemGroup>

</Project>

