// <auto-generated />
using System;
using Lyo.Validation.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Validation.Postgres.Migrations
{
    [DbContext(typeof(ValidationDbContext))]
    [Migration("20260818173222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("validation")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Validation.Postgres.Database.ValidationSchemaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConstraintsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("constraints_json");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("MessagesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("messages_json");

                    b.Property<string>("TargetTypeName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_type_name");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_validation_schema_key");

                    b.HasIndex("TargetTypeName")
                        .HasDatabaseName("ix_validation_schema_target_type");

                    b.ToTable("schema", "validation");
                });
#pragma warning restore 612, 618
        }
    }
}
