// <auto-generated />
using System;
using Lyo.Config.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Config.Postgres.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    partial class ConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("config")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Config.Postgres.Database.ConfigBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("ForEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("for_entity_id");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_entity_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("ForEntityType", "ForEntityId")
                        .HasDatabaseName("ix_config_binding_entity");

                    b.HasIndex("DefinitionId", "ForEntityType", "ForEntityId")
                        .IsUnique()
                        .HasDatabaseName("ux_config_binding_definition_entity");

                    b.ToTable("config_binding", "config");
                });

            modelBuilder.Entity("Lyo.Config.Postgres.Database.ConfigBindingRevisionEntity", b =>
                {
                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("binding_id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("BindingId", "Revision");

                    b.ToTable("config_binding_revision", "config");
                });

            modelBuilder.Entity("Lyo.Config.Postgres.Database.ConfigDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("default_value_json");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("ForEntityType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("for_entity_type");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<string>("ForValueType")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("for_value_type");

                    b.HasKey("Id");

                    b.HasIndex("ForEntityType")
                        .HasDatabaseName("ix_config_definition_entity_type");

                    b.HasIndex("ForEntityType", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_config_definition_entity_type_key");

                    b.ToTable("config_definition", "config");
                });

            modelBuilder.Entity("Lyo.Config.Postgres.Database.ConfigBindingEntity", b =>
                {
                    b.HasOne("Lyo.Config.Postgres.Database.ConfigDefinitionEntity", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Lyo.Config.Postgres.Database.ConfigBindingRevisionEntity", b =>
                {
                    b.HasOne("Lyo.Config.Postgres.Database.ConfigBindingEntity", "Binding")
                        .WithMany()
                        .HasForeignKey("BindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Binding");
                });
#pragma warning restore 612, 618
        }
    }
}
