// <auto-generated />
using System;
using Lyo.PackageMetadata.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.PackageMetadata.Postgres.Migrations
{
    [DbContext(typeof(PackageMetadataDbContext))]
    [Migration("20260502153843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("package_metadata")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.PackageMetadata.Postgres.Database.PackageMetadataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorsJson")
                        .HasColumnType("text")
                        .HasColumnName("authors_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LicenseExpression")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license_expression");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("license_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("PackageDetailsUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("package_details_url");

                    b.Property<string>("PackageFileSha512Hex")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("package_file_sha512_hex");

                    b.Property<string>("PackageTypesJson")
                        .HasColumnType("text")
                        .HasColumnName("package_types_json");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("project_url");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("repository_url");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text")
                        .HasColumnName("tags_json");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_package_name");

                    b.HasIndex("Name", "Version")
                        .HasDatabaseName("ix_package_name_version");

                    b.ToTable("package", "package_metadata");
                });

            modelBuilder.Entity("Lyo.PackageMetadata.Postgres.Database.PackageStackPrefixEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NormalizedPrefix")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("normalized_prefix");

                    b.Property<Guid>("PackageMetadataId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_metadata_id");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_prefix_normalized_prefix_unique");

                    b.HasIndex("PackageMetadataId");

                    b.ToTable("stack_prefix", "package_metadata");
                });

            modelBuilder.Entity("Lyo.PackageMetadata.Postgres.Database.PackageStackPrefixEntity", b =>
                {
                    b.HasOne("Lyo.PackageMetadata.Postgres.Database.PackageMetadataEntity", "Package")
                        .WithMany("StackPrefixes")
                        .HasForeignKey("PackageMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Lyo.PackageMetadata.Postgres.Database.PackageMetadataEntity", b =>
                {
                    b.Navigation("StackPrefixes");
                });
#pragma warning restore 612, 618
        }
    }
}
