<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mapster"/>
        <PackageReference Include="Mapster.DependencyInjection"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Npgsql"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Scalar.AspNetCore"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Data\Compression\Lyo.Compression\Lyo.Compression.csproj"/>
        <ProjectReference Include="..\..\Communication\Email\Lyo.Email.Postgres\Lyo.Email.Postgres.csproj"/>
        <ProjectReference Include="..\..\Communication\Sms\Lyo.Sms.Twilio.Postgres\Lyo.Sms.Twilio.Postgres.csproj"/>
        <ProjectReference Include="..\..\Core\Audit\Lyo.Audit.Postgres\Lyo.Audit.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\Comic\Lyo.Comic.Postgres\Lyo.Comic.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\Comment\Lyo.Comment.Postgres\Lyo.Comment.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\Note\Lyo.Note.Postgres\Lyo.Note.Postgres.csproj"/>
        <ProjectReference Include="..\..\Core\People\Lyo.People.Postgres\Lyo.People.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\Rating\Lyo.Rating.Postgres\Lyo.Rating.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\Tag\Lyo.Tag.Postgres\Lyo.Tag.Postgres.csproj"/>
        <ProjectReference Include="..\..\Data\FileMetadataStore\Lyo.FileMetadataStore.Postgres\Lyo.FileMetadataStore.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\Config\Lyo.Config.Postgres\Lyo.Config.Postgres.csproj"/>
        <ProjectReference Include="..\..\Features\ContactUs\Lyo.ContactUs.Postgres\Lyo.ContactUs.Postgres.csproj"/>
        <ProjectReference Include="..\..\Integration\Endato\Lyo.Endato.Postgres\Lyo.Endato.Postgres.csproj"/>
        <ProjectReference Include="..\..\Integration\Api\Lyo.Api.Export\Lyo.Api.Export.csproj"/>
        <ProjectReference Include="..\..\Integration\Api\Lyo.Api.Export.Csv\Lyo.Api.Export.Csv.csproj"/>
        <ProjectReference Include="..\..\Integration\Api\Lyo.Api.Export.Xlsx\Lyo.Api.Export.Xlsx.csproj"/>
        <ProjectReference Include="..\..\Integration\Api\Lyo.Api\Lyo.Api.csproj"/>
        <ProjectReference Include="..\..\Integration\Discord\Lyo.Discord.Postgres\Lyo.Discord.Postgres.csproj"/>
        <ProjectReference Include="..\..\Integration\Job\Lyo.Job.Postgres\Lyo.Job.Postgres.csproj"/>
        <ProjectReference Include="..\..\Integration\Job\Lyo.Job.Scheduler\Lyo.Job.Scheduler.csproj"/>
        <ProjectReference Include="..\..\Integration\Api\Lyo.Api.Reporting\Lyo.Api.Reporting.csproj"/>
        <ProjectReference Include="..\..\Integration\Reporting\Lyo.Reporting.Postgres\Lyo.Reporting.Postgres.csproj"/>
        <ProjectReference Include="..\..\Integration\Reporting\Lyo.Reporting.Models\Lyo.Reporting.Models.csproj"/>
        <ProjectReference Include="..\..\Communication\MessageQueue\Lyo.MessageQueue.RabbitMq\Lyo.MessageQueue.RabbitMq.csproj"/>
        <ProjectReference Include="..\..\Features\ShortUrl\Lyo.ShortUrl.Postgres\Lyo.ShortUrl.Postgres.csproj"/>
        <ProjectReference Include="..\..\Data\FileStorage\Lyo.FileStorage\Lyo.FileStorage.csproj"/>
        <ProjectReference Include="..\..\Data\FileStorage\Lyo.FileStorage.S3\Lyo.FileStorage.S3.csproj"/>
        <ProjectReference Include="..\..\Data\IOTemp\Lyo.IO.Temp\Lyo.IO.Temp.csproj"/>
        <ProjectReference Include="..\..\Core\Lock\Lyo.Lock\Lyo.Lock.csproj"/>
        <ProjectReference Include="..\..\Core\Lock\Lyo.Lock.Redis\Lyo.Lock.Redis.csproj"/>
        <ProjectReference Include="..\..\Security\KeyStore\Lyo.KeyStore\Lyo.KeyStore.csproj"/>
        <ProjectReference Include="..\..\Security\KeyStore\Lyo.KeyStore.Aws\Lyo.KeyStore.Aws.csproj"/>
        <ProjectReference Include="..\..\Security\Authentication\Lyo.Authentication\Lyo.Authentication.csproj"/>
        <ProjectReference Include="..\..\Security\Authentication\Lyo.Authentication.AspNetCore\Lyo.Authentication.AspNetCore.csproj"/>
        <ProjectReference Include="..\..\Security\Authentication\Lyo.Authentication.Postgres\Lyo.Authentication.Postgres.csproj"/>
        <ProjectReference Include="..\..\Security\Authentication\Lyo.Authentication.OpenIdConnect\Lyo.Authentication.OpenIdConnect.csproj"/>
        <ProjectReference Include="..\..\Security\Authentication\Lyo.Authentication.Google\Lyo.Authentication.Google.csproj"/>
        <ProjectReference Include="..\..\Security\Authentication\Lyo.Authentication.Keycloak\Lyo.Authentication.Keycloak.csproj"/>
    </ItemGroup>

</Project>
