<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Common\Lyo.Common.Metadata\Lyo.Common.Metadata.csproj"/>
        <ProjectReference Include="..\..\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\Lyo.DateAndTime\Lyo.DateAndTime.csproj"/>
    </ItemGroup>

</Project>
