// <auto-generated />
using System;
using Lyo.Sms.Twilio.Postgres.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lyo.Sms.Twilio.Postgres.Migrations
{
    [DbContext(typeof(TwilioSmsDbContext))]
    partial class TwilioSmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sms")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lyo.Sms.Twilio.Postgres.Database.TwilioSmsLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("id");

                    b.Property<string>("AccountSid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_sid");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_timestamp");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_timestamp");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_sent");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<long>("ElapsedTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_time_ms");

                    b.Property<string>("From")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("MediaUrlsJson")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("media_urls_json");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int?>("NumSegments")
                        .HasColumnType("integer")
                        .HasColumnName("num_segments");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("price_unit");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to");

                    b.HasKey("Id");

                    b.HasIndex("AccountSid")
                        .HasDatabaseName("ix_twilio_sms_logs_account_sid");

                    b.HasIndex("CreatedTimestamp")
                        .HasDatabaseName("ix_twilio_sms_logs_created_timestamp");

                    b.HasIndex("From")
                        .HasDatabaseName("ix_twilio_sms_logs_from");

                    b.HasIndex("IsSuccess")
                        .HasDatabaseName("ix_twilio_sms_logs_is_success");

                    b.HasIndex("IsSuccess", "CreatedTimestamp")
                        .HasDatabaseName("ix_twilio_sms_logs_is_success_created_timestamp");

                    b.HasIndex("NumSegments")
                        .HasDatabaseName("ix_twilio_sms_logs_num_segments");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_twilio_sms_logs_status");

                    b.HasIndex("To")
                        .HasDatabaseName("ix_twilio_sms_logs_to");

                    b.HasIndex("To", "CreatedTimestamp")
                        .HasDatabaseName("ix_twilio_sms_logs_to_created_timestamp");

                    b.ToTable("twilio_sms_logs", "sms");
                });
#pragma warning restore 612, 618
        }
    }
}

