// <auto-generated />
using System;
using Lyo.FileMetadataStore.Sqlite.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lyo.FileMetadataStore.Sqlite.Migrations
{
    [DbContext(typeof(SqliteFileMetadataStoreDbContext))]
    partial class SqliteFileMetadataStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Lyo.FileMetadataStore.Models.FileMetadataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<byte[]>("CompressedFileHash")
                        .HasColumnType("BLOB")
                        .HasColumnName("compressed_file_hash");

                    b.Property<long?>("CompressedFileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compressed_file_size");

                    b.Property<string>("CompressionAlgorithm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_algorithm");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<string>("DataEncryptionKeyAlgorithm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_encryption_key_algorithm");

                    b.Property<string>("DataEncryptionKeyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_encryption_key_id");

                    b.Property<string>("DataEncryptionKeyVersion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_encryption_key_version");

                    b.Property<byte?>("DekKeyMaterialBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dek_key_material_bytes");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<byte[]>("EncryptedDataEncryptionKey")
                        .HasColumnType("BLOB")
                        .HasColumnName("encrypted_data_encryption_key");

                    b.Property<byte[]>("EncryptedFileHash")
                        .HasColumnType("BLOB")
                        .HasColumnName("encrypted_file_hash");

                    b.Property<long?>("EncryptedFileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("encrypted_file_size");

                    b.Property<string>("HashAlgorithm")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_algorithm");

                    b.Property<bool>("IsCompressed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_compressed");

                    b.Property<bool>("IsEncrypted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_encrypted");

                    b.Property<string>("KeyEncryptionKeyAlgorithm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_encryption_key_algorithm");

                    b.Property<byte[]>("KeyEncryptionKeySalt")
                        .HasColumnType("BLOB")
                        .HasColumnName("key_encryption_key_salt");

                    b.Property<byte[]>("OriginalFileHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("original_file_hash");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<long>("OriginalFileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("original_file_size");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("PathPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path_prefix");

                    b.Property<byte[]>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("source_file_hash");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_name");

                    b.Property<long>("SourceFileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_file_size");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("OriginalFileHash")
                        .HasDatabaseName("ix_file_metadata_original_file_hash");

                    b.HasIndex("OriginalFileName")
                        .HasDatabaseName("ix_file_metadata_original_file_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_file_metadata_owner_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_file_metadata_tenant_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_file_metadata_timestamp");

                    b.ToTable("file_metadata", (string)null);
                });

            modelBuilder.Entity("Lyo.FileMetadataStore.Sqlite.Database.FileAuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DataEncryptionKeyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_encryption_key_id");

                    b.Property<string>("DataEncryptionKeyVersion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_encryption_key_version");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type")
                        .HasJsonPropertyName("event_type");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome")
                        .HasJsonPropertyName("outcome");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp")
                        .HasJsonPropertyName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_file_audit_events_event_type");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_audit_events_file_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_file_audit_events_timestamp");

                    b.HasIndex("TenantId", "Timestamp")
                        .HasDatabaseName("ix_file_audit_events_tenant_timestamp");

                    b.ToTable("file_audit_events", (string)null);
                });

            modelBuilder.Entity("Lyo.FileMetadataStore.Sqlite.Database.FileDataEntity", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("data");

                    b.HasKey("FileId");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_file_data_file_id");

                    b.ToTable("file_data", (string)null);
                });

            modelBuilder.Entity("Lyo.FileMetadataStore.Sqlite.Database.FileDownloadAccessLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("LastConsumedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_consumed_utc");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_downloads");

                    b.Property<DateTime?>("NotBeforeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("not_before_utc");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("WindowEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_end_utc");

                    b.Property<DateTime?>("WindowStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_start_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_file_download_access_links_expires_at_utc");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_download_access_links_file_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_file_download_access_links_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_file_download_access_links_token_hash");

                    b.HasIndex("IsRevoked", "ExpiresAtUtc")
                        .HasDatabaseName("ix_file_download_access_links_revoked_expires");

                    b.ToTable("file_download_access_links", (string)null);
                });

            modelBuilder.Entity("Lyo.FileMetadataStore.Sqlite.Database.MultipartUploadSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<bool>("Compress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compress");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<long?>("DeclaredContentLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("declared_content_length");

                    b.Property<bool>("Encrypt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("encrypt");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_utc");

                    b.Property<string>("KeyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_id");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<int>("PartSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("part_size_bytes");

                    b.Property<string>("PathPrefix")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path_prefix");

                    b.Property<int>("ProviderKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_kind");

                    b.Property<string>("ProviderState")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_state");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetFileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_file_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresUtc")
                        .HasDatabaseName("ix_multipart_upload_session_expires_utc");

                    b.HasIndex("TargetFileId")
                        .HasDatabaseName("ix_multipart_upload_session_target_file_id");

                    b.ToTable("multipart_upload_session", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
