<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\Lyo.FileStorage.S3\Lyo.FileStorage.S3.csproj"/>
    </ItemGroup>

</Project>
