<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Lyo.Privacy.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\Lyo.Privacy.AspNetCore\Lyo.Privacy.AspNetCore.csproj"/>
        <ProjectReference Include="..\Lyo.Privacy\Lyo.Privacy.csproj"/>
    </ItemGroup>

</Project>
