<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.TestHost"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Cache\Lyo.Cache\Lyo.Cache.csproj"/>
        <ProjectReference Include="..\..\..\Core\Common\Lyo.Common.Json\Lyo.Common.Json.csproj"/>
        <ProjectReference Include="..\..\..\Core\Common\Lyo.Common.Metadata\Lyo.Common.Metadata.csproj"/>
        <ProjectReference Include="..\..\..\Core\SystemInformation\Lyo.SystemInformation\Lyo.SystemInformation.csproj"/>
        <ProjectReference Include="..\..\..\Core\Diff\Lyo.Diff\Lyo.Diff.csproj"/>
        <ProjectReference Include="..\..\..\Core\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\..\..\Core\Testing\Lyo.Testing.Containers\Lyo.Testing.Containers.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Api\Lyo.Api\Lyo.Api.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Api\Lyo.Api.Client\Lyo.Api.Client.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Api\Lyo.Api.Models\Lyo.Api.Models.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Http\Lyo.Http.Client\Lyo.Http.Client.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Drift\Lyo.Drift.Agent\Lyo.Drift.Agent.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Drift\Lyo.Drift.Api\Lyo.Drift.Api.csproj"/>
        <ProjectReference Include="..\..\..\Apps\Drift\Lyo.Drift.Client\Lyo.Drift.Client.csproj"/>
        <ProjectReference Include="..\Lyo.Drift.Models\Lyo.Drift.Models.csproj"/>
        <ProjectReference Include="..\Lyo.Drift.Postgres\Lyo.Drift.Postgres.csproj"/>
        <ProjectReference Include="..\..\..\Data\Query\Lyo.Query.Models\Lyo.Query.Models.csproj"/>
        <ProjectReference Include="..\..\..\Data\FileSystemWatcher\Lyo.FileSystemWatcher.Models\Lyo.FileSystemWatcher.Models.csproj"/>
    </ItemGroup>

</Project>
