<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Core\Testing\Lyo.Testing\Lyo.Testing.csproj"/>
        <ProjectReference Include="..\..\..\Core\Testing\Lyo.Testing.Containers\Lyo.Testing.Containers.csproj"/>
        <ProjectReference Include="..\Lyo.Http.Client.Flared\Lyo.Http.Client.Flared.csproj"/>
        <ProjectReference Include="..\Lyo.Http.Client\Lyo.Http.Client.csproj"/>
    </ItemGroup>

</Project>
